// Real page/CSS/module in Chromium; room/session data is a local fixture.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async r=>{const u=new URL(r.request().url());const f=path.join(process.cwd(),'public',u.pathname==='/'?'index.html':u.pathname);if(u.hostname!=='app.test'||!fs.existsSync(f))return r.abort();let body=fs.readFileSync(f);if(f.endsWith('index.html'))body=Buffer.from(body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''));await r.fulfill({body,contentType:f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':undefined});});
 await page.goto('https://app.test/');await page.evaluate(()=>{document.querySelector('#appSplash')?.remove();document.querySelector('#loginScreen').classList.add('hidden');document.querySelector('#mainApp').classList.remove('hidden');document.querySelectorAll('#mainApp>.card').forEach(e=>e.classList.add('hidden'));window.setInterval=()=>0;window.currentStudent={studentId:'me'};window.hsmEnsureStudentSession_=async()=>'test';window.hideAllStudentMainScreens_=()=>{};window.setActiveMenu=()=>{};window.HANSALMAE_CONFIG={apiUrl:'https://app.test/api'};});
 let code=fs.readFileSync('public/battle-rooms.js','utf8').replace("if(document.readyState==='loading')","window.arenaTest={init,accept,open:()=>root.classList.remove('hidden')};if(document.readyState==='loading')");await page.addScriptTag({content:code});await page.evaluate(()=>{arenaTest.init();arenaTest.open();});
 const results=[];
 for(const width of [320,393,430,768,1280])for(let n=2;n<=8;n++){
  await page.setViewportSize({width,height:852});
  await page.evaluate(n=>{const now=Date.now();arenaTest.accept({id:'test',title:'단어 대전',me:'p0',host:'p0',status:'playing',members:Array.from({length:n},(_,i)=>({id:'p'+i,name:i===0?'박노아':'친구'+i,score:i===0?5:3,seat:i,answered:false,left:false,image:'./images/emblems/title-chick.png'})),settings:{count:10,seconds:10,title:'중등단어',start:1,end:1},round:2,roundAt:new Date(now-100).toISOString(),deadline:new Date(now+9900).toISOString(),serverNow:new Date(now).toISOString(),question:{prompt:'story',mode:'engToKor',options:[{id:'a',text:'이야기, (건물의)층'},{id:'b',text:'가지고 있다, 먹다, ~하게 하다, 당하다'},{id:'c',text:'일, 일자리'},{id:'d',text:'~을 놀리다'}]},chat:[]});document.querySelectorAll('.br-bubble').forEach(e=>{e.innerHTML='<span><span class="br-sticker br-sticker-smile"></span></span>';e.classList.add('is-showing');});},n);
  await page.waitForTimeout(220);
  const g=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};return {viewport:innerWidth,scroll:document.documentElement.scrollWidth,cols:getComputedStyle(document.querySelector('.br-player-grid')).gridTemplateColumns.split(' ').length,stage:rect(document.querySelector('.br-players')),players:[...document.querySelectorAll('[data-player]')].map(p=>({seat:rect(p),avatar:rect(p.querySelector('.br-mini-character')),bubble:rect(p.querySelector('.br-bubble')),score:rect(p.querySelector('b')),name:rect(p.querySelector('.br-player-copy')),crown:p.querySelector('.br-leader:not([hidden])')?rect(p.querySelector('.br-leader')):null})),buttons:[...document.querySelectorAll('[data-br="emoji"]')].map(rect)}});
  assert(g.scroll<=width+1,`overflow ${width}/${n}`);assert.equal(g.cols,Math.min(n,4));
  for(const p of g.players){assert(p.bubble.y>=g.stage.y,`bubble outside stage ${width}/${n}`);assert(p.avatar.width>=(n<=2?66:n<=4?(width<=350?48:54):(width<=350?44:48)));assert(p.bubble.bottom<=p.avatar.y+1);assert(p.name.bottom<=p.score.y+1);if(p.crown)assert(p.crown.bottom<=p.score.bottom+1);}
  for(let i=0;i<g.players.length;i++)for(let j=i+1;j<g.players.length;j++){const a=g.players[i].seat,b=g.players[j].seat;assert(a.right<=b.x+1||b.right<=a.x+1||a.bottom<=b.y+1||b.bottom<=a.y+1,`overlap ${width}/${n}`);}
  assert(g.buttons.every(b=>b.width>=44&&b.height>=44));results.push({width,n,cols:g.cols,avatar:g.players[0].avatar.width,stage:Math.round(g.stage.height)});
  if(width===393&&[2,4,8].includes(n))await page.screenshot({path:`/tmp/arena-layout-${n}.png`,fullPage:true});
 }
 await page.setViewportSize({width:393,height:852});
 await page.evaluate(()=>{const now=Date.now();arenaTest.accept({id:'sync-test',title:'단어 대전',me:'p0',host:'p0',status:'playing',syncEnabled:true,preparing:true,round:0,roundAt:null,deadline:null,serverNow:new Date(now).toISOString(),members:Array.from({length:4},(_,i)=>({id:'p'+i,name:i?'친구'+i:'박노아',score:0,loaded:i<3,image:'./images/emblems/title-chick.png'})),settings:{count:10,seconds:10,title:'중등단어'},question:null,preparedQuestion:{prompt:'story',mode:'engToKor',correctId:null,options:[{id:'a',text:'이야기'}]},chat:[]});});
 assert.equal(await page.locator('[data-br="answer"]').count(),0);
 assert.equal(await page.locator('#brTimer').textContent(),'준비 중');
 await page.screenshot({path:'/tmp/arena-sync-ready.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify(results));console.log('PASS 35 viewport/roster cases: 2–8 players, columns, avatar sizes, reaction bounds, no seat overlap, no horizontal overflow, 44px touch targets.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
