import {JSDOM} from 'jsdom';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const html=readFileSync('public/index.html','utf8');
const a=html.indexOf('id="wrongNotebookScreen"'),b=html.indexOf('<!-- 나만의 단어장 화면 -->',a);
const dom=new JSDOM('<div '+html.slice(a,b),{runScripts:'outside-only',url:'https://example.test'});const w=dom.window,d=w.document,$=id=>d.getElementById(id);
w.eval('var wrongNotebookWords=[],wrongSelectionMode_=false,wrongNotebookFilter="active",currentLoginToken="a",currentTestContext={};');
w.scrollTo=()=>{};w.alert=message=>{throw Error(message);};
w.eval(html.slice(html.indexOf('    function getSelectedWrongRows_()'),html.indexOf('    function deleteSelectedMasteredWrongWords_')));
w.batchSaveCheckedWrongWords_=()=>{};w.hsmRefreshWrongNotebookImmediately_=()=>{};
w.renderWrongNotebook=()=>{};
w.eval(readFileSync('public/wrong-review.js','utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));
const words=Array.from({length:8},(_,i)=>({rowNumber:i+1,rawSheetName:i<6?'중등단어DB':'고등단어DB',word:'word'+i,meaning:'뜻'+i,day:1,mastered:false,example:i===0?'example':''}));
w.wrongNotebookWords=words;
w.showWrongTestSetup();assert.equal($('wrongTestSheetName').value,'all');assert.equal(w.getSelectedWrongTestWords().length,8);assert.equal($('wrongTestQuestionCount').value,'8');
$('wrongTestSheetName').value='고등단어DB';w.updateWrongTestAvailableCount();assert.equal($('wrongTestQuestionCount').max,'2');
let result;w.createQuestions=(targets,options)=>{result={targets,options};};
let fail=false;w.google={script:{get run(){return {withSuccessHandler(fn){this.success=fn;return this;},withFailureHandler(fn){this.failure=fn;return this;},getWords(name){if(fail)this.failure(Error('offline'));else this.success(Array.from({length:5},(_,i)=>({word:'pool'+i,meaning:'보기'+i,exampleAnswer:'pool'+i,day:1})));}}}}};
await w.startWrongAnswerTest();assert.equal(result.targets.length,2);assert.equal(result.options.requestedCount,2);assert.ok(result.targets.every(x=>x.sheetName==='고등단어DB'));assert.equal(result.options.noRepeat,true);
w.showWrongTestSetup();await w.startWrongAnswerTest();assert.equal(result.targets.length,8);assert.equal(new Set(result.targets.map(x=>x.sheetName)).size,2);
$('wrongNotebookList').innerHTML='<input class="wrong-batch-check" type="checkbox" value="7" checked><input class="wrong-batch-check" type="checkbox" value="1">';
w.hsmTestSelectedWrong_();assert.equal(w.getSelectedWrongTestWords().length,1);await w.startWrongAnswerTest();assert.equal(result.targets[0].word,'word6');assert.equal(result.options.requestedCount,1);
$('wrongTestQuestionMode').value='example';w.updateWrongTestAvailableCount();assert.equal($('wrongTestQuestionCount').max,'0');assert.equal($('wrongTestSetupScreen').querySelector('.wrong-test-button-row button').disabled,true);
$('wrongTestQuestionMode').value='engToKor';w.updateWrongTestAvailableCount();result=null;fail=true;await w.startWrongAnswerTest();assert.equal(result,null);assert.match($('wrongTestAvailableText').textContent,/offline/);
w.clearWrongSelection_();assert.equal($('hsmSelectedSave').disabled,true);assert.equal($('hsmSelectedExam').disabled,true);
await new Promise(r=>w.setTimeout(r,0));dom.window.close();console.log('PASS mixed categories, source preservation, selected-only single word, example availability, failed lookup and empty selection');
