// Layout fixtures use real markup/styles; no authentication or production data.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
for(const touch of [false,true]){
const context=await browser.newContext({viewport:{width:1366,height:900},hasTouch:touch,isMobile:touch});
await context.route('**/*',async r=>{const u=new URL(r.request().url()),p=path.join(process.cwd(),'public',u.pathname==='/'?'index.html':u.pathname);if(u.hostname!=='app.test'||!fs.existsSync(p))return r.abort();let data=fs.readFileSync(p);if(p.endsWith('index.html'))data=Buffer.from(data.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''));await r.fulfill({body:data,contentType:p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':undefined});});
const page=await context.newPage();await page.goto('https://app.test/');await page.evaluate(()=>{document.getElementById('appSplash').remove();document.getElementById('loginScreen').classList.add('hidden');document.getElementById('mainApp').classList.remove('hidden');document.body.classList.add('hsm-student-app-open','hsm-launcher-open');document.getElementById('hsmLauncherHome').classList.remove('hidden');});await page.evaluate(()=>document.fonts.ready);
if(touch){
 for(const size of [{width:393,height:852},{width:852,height:393},{width:820,height:1180},{width:1180,height:820}]){
  await page.setViewportSize(size);const snap=()=>page.evaluate(()=>[...document.querySelectorAll('#hsmLauncherHome,#hsmLauncherHome *,#mainApp .topbar,#hsmMobileNav')].map(x=>{const r=x.getBoundingClientRect(),s=getComputedStyle(x);return[r.x,r.y,r.width,r.height,s.display,s.padding,s.fontSize]}));const before=await snap();await page.evaluate(()=>document.querySelector('link[href*="desktop-layout.css"]').disabled=true);assert.deepEqual(before,await snap());await page.evaluate(()=>document.querySelector('link[href*="desktop-layout.css"]').disabled=false);
 }console.log('PASS no phone/tablet layout change');
}else{
 for(const width of [1024,1366,1440,1920]){
  await page.setViewportSize({width,height:900});const r=await page.evaluate(()=>{const a=document.querySelector('.hsm-launcher-hero').getBoundingClientRect(),b=document.getElementById('hsmHomeBattle').getBoundingClientRect();return{a:a.toJSON(),b:b.toJSON(),columns:getComputedStyle(document.querySelector('.hsm-launcher-study-grid')).gridTemplateColumns.split(' ').length,overflow:document.documentElement.scrollWidth>innerWidth};});assert.equal(r.a.top,r.b.top);assert(r.a.right<r.b.left);assert.equal(r.columns,3);assert(!r.overflow);if(width===1366){await page.locator('#hsmHomeBattle img').evaluate(img=>img.decode());await page.screenshot({path:'/tmp/desktop129-home.png'});}
 }
 await page.evaluate(()=>{document.body.classList.remove('hsm-launcher-open');document.getElementById('hsmLauncherHome').classList.add('hidden');document.querySelectorAll('#mainApp>.card').forEach(e=>e.classList.add('hidden'));document.getElementById('vocabScreen').classList.remove('hidden');document.getElementById('wordList').innerHTML=Array.from({length:12},(_,i)=>`<article class="word-card hsm-unified-word"><div class="word-content"><div class="hsm-word-meta">수능단어 · Day 1</div><div class="word-title hsm-word-heading"><span class="word-number hsm-word-number">${i+1}</span><span class="word-English">transformation</span></div><div class="word-meaning">변화, 변형</div><div class="word-example">A small change can make a meaningful difference in our daily lives.</div><div class="word-translation">작은 변화가 일상에 의미 있는 차이를 만들 수 있다.</div></div></article>`).join('');});
 for(const width of [1024,1366,1440,1920]){
  await page.setViewportSize({width,height:900});const r=await page.evaluate(()=>({columns:getComputedStyle(document.getElementById('wordList')).gridTemplateColumns.split(' ').length,overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll('.topbar-menu>button')].filter(e=>e.getBoundingClientRect().width).map(e=>e.getBoundingClientRect().right)}));assert.equal(r.columns,width>=1440?3:2);assert((await page.locator('#wordList>.word-card').first().boundingBox()).width>300);assert(!r.overflow);assert(r.buttons.every(x=>x<=width));if(width===1440)await page.screenshot({path:'/tmp/desktop129-vocab.png'});
 }
 await page.evaluate(()=>{document.getElementById('vocabScreen').classList.add('hidden');document.getElementById('teacherExamTakingScreen').classList.remove('hidden');});const exam=await page.locator('#teacherExamTakingScreen').boundingBox();assert(exam.width<=800);assert(Math.abs(exam.x-(1920-exam.width)/2)<2);console.log('PASS desktop home, menus, vocabulary columns, centered exam at 1024/1366/1440/1920');
}
await context.close();}await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
