import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const html=readFileSync('public/index.html','utf8');
const section=html.slice(html.indexOf('      <!-- 테스트 시작 화면 -->'),html.indexOf('      <!-- 시험 문제 화면 -->'));
const wrongSection=html.slice(html.indexOf('        id="wrongTestSetupScreen"')-20,html.indexOf('      <!-- 나만의 단어장 화면 -->'));
const dom=new JSDOM(wrongSection+section+'<select id="vocabSheetName"></select><label for="vocabDay">Day</label><select id="vocabDay"></select>',{runScripts:'outside-only'});
const w=dom.window, d=w.document, el=id=>d.getElementById(id);
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
for(const id of ['sheetName','vocabSheetName'])el(id).innerHTML=['중등','고등','수능'].map(x=>'<option>'+x+'단어DB</option>').join('');
for(const id of ['startDay','endDay','vocabDay'])el(id).innerHTML=Array.from({length:70},(_,i)=>'<option>'+ (i+1)+'</option>').join('');
el('endDay').value='70';
w.eval(readFileSync('public/test-setup.js','utf8'));
d.dispatchEvent(new w.Event('DOMContentLoaded'));
el('wrongTestSheetName').innerHTML='<option value="middle">중등단어DB (6개)</option><option value="high">고등단어DB (8개)</option>';
await new Promise(resolve=>w.setTimeout(resolve,0));
let changed=0;el('wrongTestSheetName').addEventListener('change',()=>changed++);
assert.equal(el('wrongTestQuestionMode').value,'engToKor');
assert.equal(el('wrongTestSheetName').hidden,true);
el('hsmWrongSheets').querySelector('[data-value="high"]').click();
assert.equal(el('wrongTestSheetName').value,'high');assert.equal(changed,1);
assert.equal(el('hsmWrongSheets').textContent.includes('DB'),false);
el('hsmWrongModes').querySelector('[data-value="example"]').click();
assert.equal(el('wrongTestQuestionMode').value,'example');
el('wrongTestQuestionCount').max='6';el('wrongTestQuestionCount').value='6';
w.dispatchEvent(new w.Event('hsm:wrong-count'));
assert.equal(d.querySelector('.hsm-wrong-counts').textContent,'전체 6개');
assert.equal(d.querySelector('.hsm-wrong-counts [aria-pressed="true"]').dataset.value,'6');
el('wrongTestQuestionCount').value='30';el('wrongTestQuestionCount').dispatchEvent(new w.Event('input'));
assert.equal(el('wrongTestQuestionCount').value,'6');
el('wrongTestQuestionCount').max='35';w.dispatchEvent(new w.Event('hsm:wrong-count'));
d.querySelector('.hsm-wrong-counts [data-value="30"]').click();
assert.equal(el('wrongTestQuestionCount').value,'30');
// Exercise the actual start handler, including bypassing the input event.
w.eval('var currentTestContext=null;');
w.getSelectedWrongTestWords=()=>Array.from({length:6},(_,i)=>({word:'word'+i,meaning:'meaning'+i,day:1,example:i<2?'example':''}));
w.eval(html.slice(html.indexOf('    function getWrongTestQuestionLimit()'),html.indexOf('    function setWrongNotebookFilter(')));
let started=null,alerts=[];w.createQuestions=(words,options)=>{started=options;};w.HSMDialog={alert:(...a)=>w.alert(...a),confirm:async(...a)=>w.confirm(...a),prompt:async(...a)=>w.prompt(...a)};w.alert=message=>alerts.push(message);
el('wrongTestQuestionMode').value='engToKor';el('wrongTestQuestionCount').value='30';
w.startWrongAnswerTest();assert.equal(started,null);assert.equal(el('wrongTestQuestionCount').value,'6');assert.equal(alerts.length,1);
w.startWrongAnswerTest();assert.equal(started.requestedCount,6);assert.equal(started.noRepeat,true);
el('wrongTestQuestionMode').value='example';w.updateWrongTestAvailableCount();
assert.equal(el('wrongTestQuestionCount').max,'2');assert.equal(el('wrongTestQuestionCount').value,'2');
w.startWrongAnswerTest();assert.equal(started.requestedCount,2);
// Run the question builder through question generation, before screen effects.
const builder=html.slice(html.indexOf('    function createQuestions(words, options) {'),html.indexOf('      currentIndex = 0;',html.indexOf('    function createQuestions(words, options) {')))+'return questions; }';
w.eval('var allWords=[],questions=[];');w.shuffleArray=items=>Array.from(items).reverse();w.eval(builder);
for(const mode of ['engToKor','korToEng','mixed','random','example']){
 const words=w.getSelectedWrongTestWords();
 const generated=w.createQuestions(words,{requestedCount:mode==='example'?2:6,questionMode:mode,noRepeat:true});
 assert.equal(generated.length,mode==='example'?2:6);
 assert.equal(new Set(generated.map(q=>q.data.word)).size,generated.length);
}
for(const [grade,expected] of [['중1','중등'],['중3','중등'],['고1','고등'],['고2','고등'],['고3','수능']]){
 w.hsmSetupApplyStudentDefaults_({studentId:grade,studentName:'테스트',grade});
 assert.equal(el('sheetName').value,expected+'단어DB');
 assert.equal(el('vocabSheetName').value,expected+'단어DB');
 assert.equal(el('questionMode').value,'engToKor');
 assert.equal(el('questionCount').value,'30');
}
el('hsmSetupSheets').querySelector('[data-value="중등단어DB"]').click();
el('hsmVocabSheets').querySelector('[data-value="중등단어DB"]').click();
assert.equal(el('vocabSheetName').value,'중등단어DB');
assert.equal(el('hsmVocabSheets').querySelector('[data-value="중등단어DB"]').getAttribute('aria-pressed'),'true');
el('hsmSetupModes').querySelector('[data-value="mixed"]').click();
el('hsmSetupCounts').querySelector('[data-value="20"]').click();
w.hsmSetupApplyStudentDefaults_({studentId:'고3',grade:'고3'});
assert.equal(el('sheetName').value,'중등단어DB');
assert.equal(el('vocabSheetName').value,'중등단어DB');
assert.equal(el('questionMode').value,'mixed');
assert.equal(el('questionCount').value,'20');
el('hsmSetupCounts').querySelector('[data-value="custom"]').click();
assert.equal(el('questionCount').hidden,false);
el('questionCount').value='45';el('questionCount').dispatchEvent(new w.Event('input'));
assert.equal(el('hsmSetupCounts').querySelector('[data-value="custom"]').getAttribute('aria-pressed'),'true');
el('hsmPickendDay').click();el('hsmDayGrid').querySelector('[aria-label="Day 3"]').click();
el('hsmPickstartDay').click();el('hsmDayGrid').querySelector('[aria-label="Day 50"]').click();
assert.equal(el('endDay').value,'50');
assert.equal(el('hsmDayPicker').open,false);
el('hsmPickendDay').click();
assert.equal(el('hsmDayGrid').children.length,70);
assert.equal(el('hsmDayGrid').lastElementChild.getAttribute('aria-label'),'Day 70');
el('hsmDayGrid').lastElementChild.click();
assert.equal(el('endDay').value,'70');
el('hsmPickendDay').click();el('hsmDayClose').click();
assert.equal(el('hsmDayPicker').open,false);
el('hsmPickendDay').click();el('hsmDayAll').click();
assert.equal(el('startDay').value,'1');assert.equal(el('endDay').value,'70');
w.hsmSetupApplyStudentDefaults_({studentId:'new',grade:'고1'});
assert.equal(el('questionCount').value,'30');assert.equal(el('questionCount').hidden,true);
let selectedVocabDay='';el('vocabDay').addEventListener('change',()=>selectedVocabDay=el('vocabDay').value);
el('hsmPickvocabDay').click();assert.equal(el('hsmDayAll').hidden,true);
el('hsmDayGrid').querySelector('[aria-label="Day 12"]').click();
assert.equal(selectedVocabDay,'12');assert.equal(el('hsmPickvocabDay').textContent,'Day 12 ⌄');
assert.equal(el('startDay').value,'1');assert.equal(el('endDay').value,'70');
el('hsmPickvocabDay').click();assert.equal(el('hsmDayGrid').querySelector('[aria-label="Day 12"]').getAttribute('aria-pressed'),'true');el('hsmDayClose').click();
el('hsmPickstartDay').click();assert.equal(el('hsmDayAll').hidden,false);el('hsmDayClose').click();
const pending=[];
w.google={script:{get run(){const req={};return {withSuccessHandler(fn){req.ok=fn;return this;},withFailureHandler(fn){req.fail=fn;return this;},getDays(sheet){req.sheet=sheet;pending.push(req);}};}}};
w.eval(html.slice(html.indexOf('    let testDaysRequestId = 0;'),html.indexOf('    function loadVocabDays()')));
w.loadTestDays();el('sheetName').value='수능단어DB';w.loadTestDays();
pending[1].ok([1,2,3]);pending[0].ok([9,10]);
assert.deepEqual(Array.from(el('startDay').options,o=>o.value),['1','2','3']);
assert.equal(el('startButton').disabled,false);
w.loadTestDays();pending[2].fail(new Error('test'));
assert.equal(el('startButton').disabled,true);
w.loadTestDays();pending[3].ok([]);
assert.equal(el('startButton').disabled,true);
console.log('Test setup: grade defaults, manual choices, 30 questions, Day bounds, stale responses and failures passed.');
el('vocabDay').disabled=true;
await new Promise(resolve=>w.setTimeout(resolve,0));
assert.equal(el('hsmPickvocabDay').disabled,true);
el('vocabDay').disabled=false;el('vocabDay').innerHTML='<option value="1">Day 1</option>';
await new Promise(resolve=>w.setTimeout(resolve,0));
assert.equal(el('hsmPickvocabDay').textContent,'Day 1 ⌄');
assert.equal(el('hsmPickvocabDay').disabled,false);
w.close();

// Real notebook loaders: a saved result refresh must update the snapshot and ignore old responses.
const noteDom=new JSDOM('<div id="wrongNotebookLoading"></div><div id="wrongNotebookSummary"></div><div id="wrongNotebookPreview"></div><div id="wrongNotebookScreen"></div>'+wrongSection,{runScripts:'outside-only',url:'https://example.test'});
const nw=noteDom.window,nd=nw.document;
nw.eval('var currentLoginToken="student-a",currentStudent={studentId:"a"},wrongNotebookWords=[];');
nw.renderWrongNotebook=()=>{};nw.scrollTo=()=>{};nw.HSMDialog={alert:(...a)=>nw.alert(...a),confirm:async(...a)=>nw.confirm(...a),prompt:async(...a)=>nw.prompt(...a)};nw.alert=message=>{throw Error(message);};
nw.eval(html.slice(html.indexOf('    function showWrongTestSetup('),html.indexOf('    function startWrongAnswerTest()')));
const fast=html.split('<script id="hsm-wrong-notebook-fast-v4">')[1].split('</script>')[0];nw.eval(fast);
const immediate=html.split('<script id="hsm-wrong-note-immediate-refresh">')[1].split('</script>')[0];nw.eval(immediate);
const notePending=[];
nw.google={script:{get run(){const call={withSuccessHandler(fn){this.success=fn;return this;},withFailureHandler(fn){this.failure=fn;return this;},getWrongNotebook(token){notePending.push(this);}};return call;}}};
const oldResult={success:true,words:Array.from({length:6},(_,i)=>({word:'m'+i,rawSheetName:'중등단어DB',sheetName:'중등단어DB',mastered:false})),activeCount:6};
const freshResult={success:true,words:oldResult.words.concat([{word:'h1',rawSheetName:'고등단어DB'},{word:'h2',rawSheetName:'고등단어DB'}]),activeCount:8};
nw.applyWrongNotebookResult_(oldResult);
nw.hsmFetchLatestWrongNotebook_();
nw.hsmRefreshWrongNotebookImmediately_();
assert.equal(nw.readWrongNotebookSnapshot_(),null);
notePending[1].success(freshResult);notePending[0].success(oldResult);
assert.equal(nw.readWrongNotebookSnapshot_().activeCount,8);
assert.match(nd.getElementById('wrongNotebookSummary').textContent,/8개/);
nw.showWrongTestSetup();
const high=Array.from(nd.getElementById('wrongTestSheetName').options).find(o=>o.value==='고등단어DB');
assert.equal(high.disabled,true);assert.match(high.textContent,/2개.*4개부터 시험 가능/);
assert.equal(nd.getElementById('wrongTestSheetName').value,'중등단어DB');
nw.hsmFetchLatestWrongNotebook_();nw.eval('currentLoginToken="student-b"');notePending[2].success(oldResult);
assert.equal(nw.readWrongNotebookSnapshot_().activeCount,8);
noteDom.window.close();
console.log('PASS saved wrong answers update snapshot; stale/account-switched reads ignored; two-word categories remain visible');

