import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const source=n=>fs.readFileSync(new URL('../public/'+n,import.meta.url),'utf8');
const html=source('index.html');
const head=html.slice(html.indexOf('<head>')+6,html.indexOf('</head>')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,tag=>{const h=tag.match(/href="\.\/([^"?]+)(?:\?[^" ]*)?"/);return /rel="stylesheet"/.test(tag)&&h?'<style>'+source(h[1])+'</style>':''});
const body=html.slice(html.indexOf('<body>')+6,html.indexOf('</body>')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const dom=new JSDOM('<head>'+head+'</head><body>'+body+'</body>',{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window,d=w.document,nav=d.getElementById('hsmMobileNav');
assert.equal(nav.parentElement,d.body);assert.equal(d.getElementById('hsmMobileNavLayer'),null);
assert.equal(nav.querySelectorAll('[data-mobile-menu]').length,6);
// Expand mobile media rules for the cascade test; jsdom does not do mobile layout.
const css=source('design-v2-mobile-nav.css');const sheet=d.createElement('style');sheet.textContent=css;d.head.append(sheet);
const active=d.createElement('style');active.textContent=[...sheet.sheet.cssRules].map(r=>r.type===4?(r.conditionText.includes('max-width')?[...r.cssRules].map(x=>x.cssText).join('\n'):''):r.cssText).join('\n');sheet.remove();d.head.insertBefore(active,d.getElementById('hsm-launcher-home-style'));
d.body.classList.add('hsm-student-app-open');
const get=el=>w.getComputedStyle(el);
assert.equal(get(nav).position,'fixed');assert.equal(get(nav).bottom,'0px');assert.equal(get(nav).left,'0px');assert.equal(get(nav).right,'0px');
assert.equal(get(nav).display,'grid');
assert.match(html,/body\.hsm-launcher-open #hsmMobileNav,[\s\S]{0,100}display: none !important/);
d.body.classList.remove('hsm-student-app-open');assert.equal(get(nav).display,'none');
w.close();console.log('PASS original fixed-bottom navigation, six menus and home/login visibility (not device layout verification)');
