import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import {gradeEvidence} from '../supabase/functions/api/grading.mts';
const root=new URL('../public/',import.meta.url);
const source=n=>fs.readFileSync(new URL(n,root),'utf8');
const html=source('index.html');
const sync=html.slice(html.indexOf('function syncStoredSession_()'),html.indexOf('let coordinatedRefresh_ = null;'));
const values={hansalmaeStudentToken:'B-token',hansalmaeStudentInfo:JSON.stringify({studentId:'B'})};
const ctx={currentStudent:{studentId:'A'},currentLoginToken:'A-token',localStorage:{getItem:k=>values[k]},makeError:message=>new Error(message)};
vm.createContext(ctx);assert.throws(()=>vm.runInContext(sync+'syncStoredSession_();',ctx),/계정이 변경/);assert.equal(ctx.currentLoginToken,'A-token');
values.hansalmaeStudentInfo=JSON.stringify({studentId:'A'});values.hansalmaeStudentToken='renewed-A';vm.runInContext('syncStoredSession_();',ctx);assert.equal(ctx.currentLoginToken,'renewed-A');
console.log('PASS cross-account blocked; same-account token renewal allowed');
const d=new JSDOM('<div class="panel"><input id="studentSearch" type="search"><input id="title"></div>',{url:'https://example.test/teacher.html',runScripts:'outside-only'});const w=d.window;
w.eval(source('app-update.js'));w.document.querySelector('#studentSearch').dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok(!w.hsmTeacherDirty_);w.document.querySelector('#title').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.hsmTeacherDirty_,true);
w.localStorage.setItem('hansalmaeStudentInfo',JSON.stringify({studentId:'A'}));w.localStorage.setItem('hansalmaeStudentToken','fixture');
w.localStorage.setItem('hsmSchoolOutbox:A',JSON.stringify([{owner:'A',action:'bad',payload:{requestId:'1'}},{owner:'A',action:'good',payload:{requestId:'2'}}]));w.eval(source('school-runtime.js'));const calls=[];w.hsmSchoolApi_=async a=>{calls.push(a);if(a==='bad')throw Error('deleted book');};w.dispatchEvent(new w.Event('online'));await new Promise(r=>setTimeout(r,25));assert.deepEqual(calls,['bad','good']);assert.equal(JSON.parse(w.localStorage.getItem('hsmSchoolOutbox:A')).length,1);d.window.close();console.log('PASS failed result does not block next save; searches do not block updates');
const candidates=[{word:'run',meaning:'달리다',day:1,example_answer:'running',word_sets:{name:'Book'}}];
const evidence=[{word:'run',day:1,sheetName:'Book',type:'example',answer:'run',correct:true},{word:'run',day:1,sheetName:'Book',type:'engToKor',answer:'달리다'}];
const result=gradeEvidence(evidence,candidates);assert.equal(result.correct,1);assert.equal(result.score,50);assert.equal(result.wrongs.length,1);
assert.throws(()=>gradeEvidence([{...evidence[0],word:'invented'}],candidates),/단어/);assert.throws(()=>gradeEvidence([],candidates),/답안/);
console.log('PASS server grading ignores forged correctness and rejects unknown words');
