import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const html=readFileSync('public/index.html','utf8');
const section=html.slice(html.indexOf('      <!-- 테스트 시작 화면 -->'),html.indexOf('      <!-- 시험 문제 화면 -->'));
const dom=new JSDOM(section+'<select id="vocabSheetName"></select><label for="vocabDay">Day</label><select id="vocabDay"></select>',{runScripts:'outside-only'});
const w=dom.window, d=w.document, el=id=>d.getElementById(id);
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
for(const id of ['sheetName','vocabSheetName'])el(id).innerHTML=['중등','고등','수능'].map(x=>'<option>'+x+'단어DB</option>').join('');
for(const id of ['startDay','endDay','vocabDay'])el(id).innerHTML=Array.from({length:70},(_,i)=>'<option>'+ (i+1)+'</option>').join('');
el('endDay').value='70';
w.eval(readFileSync('public/test-setup.js','utf8'));
d.dispatchEvent(new w.Event('DOMContentLoaded'));
for(const [grade,expected] of [['중1','중등'],['중3','중등'],['고1','고등'],['고2','고등'],['고3','수능']]){
 w.hsmSetupApplyStudentDefaults_({studentId:grade,studentName:'테스트',grade});
 assert.equal(el('sheetName').value,expected+'단어DB');
 assert.equal(el('vocabSheetName').value,expected+'단어DB');
 assert.equal(el('questionMode').value,'engToKor');
 assert.equal(el('questionCount').value,'30');
}
el('hsmSetupSheets').querySelector('[data-value="중등단어DB"]').click();
el('hsmVocabSheets').querySelector('[data-value="중등단어DB"]').click();
assert.equal(el('vocabSheetName').value,'중등단어DB');
assert.equal(el('hsmVocabSheets').querySelector('[data-value="중등단어DB"]').getAttribute('aria-pressed'),'true');
el('hsmSetupModes').querySelector('[data-value="mixed"]').click();
el('hsmSetupCounts').querySelector('[data-value="20"]').click();
w.hsmSetupApplyStudentDefaults_({studentId:'고3',grade:'고3'});
assert.equal(el('sheetName').value,'중등단어DB');
assert.equal(el('vocabSheetName').value,'중등단어DB');
assert.equal(el('questionMode').value,'mixed');
assert.equal(el('questionCount').value,'20');
el('hsmSetupCounts').querySelector('[data-value="custom"]').click();
assert.equal(el('questionCount').hidden,false);
el('questionCount').value='45';el('questionCount').dispatchEvent(new w.Event('input'));
assert.equal(el('hsmSetupCounts').querySelector('[data-value="custom"]').getAttribute('aria-pressed'),'true');
el('hsmPickendDay').click();el('hsmDayGrid').querySelector('[aria-label="Day 3"]').click();
el('hsmPickstartDay').click();el('hsmDayGrid').querySelector('[aria-label="Day 50"]').click();
assert.equal(el('endDay').value,'50');
assert.equal(el('hsmDayPicker').open,false);
el('hsmPickendDay').click();el('hsmDayAll').click();
assert.equal(el('startDay').value,'1');assert.equal(el('endDay').value,'70');
w.hsmSetupApplyStudentDefaults_({studentId:'new',grade:'고1'});
assert.equal(el('questionCount').value,'30');assert.equal(el('questionCount').hidden,true);
let selectedVocabDay='';el('vocabDay').addEventListener('change',()=>selectedVocabDay=el('vocabDay').value);
el('hsmPickvocabDay').click();assert.equal(el('hsmDayAll').hidden,true);
el('hsmDayGrid').querySelector('[aria-label="Day 12"]').click();
assert.equal(selectedVocabDay,'12');assert.equal(el('hsmPickvocabDay').textContent,'Day 12 ⌄');
assert.equal(el('startDay').value,'1');assert.equal(el('endDay').value,'70');
el('hsmPickvocabDay').click();assert.equal(el('hsmDayGrid').querySelector('[aria-label="Day 12"]').getAttribute('aria-pressed'),'true');el('hsmDayClose').click();
el('hsmPickstartDay').click();assert.equal(el('hsmDayAll').hidden,false);el('hsmDayClose').click();
const pending=[];
w.google={script:{get run(){const req={};return {withSuccessHandler(fn){req.ok=fn;return this;},withFailureHandler(fn){req.fail=fn;return this;},getDays(sheet){req.sheet=sheet;pending.push(req);}};}}};
w.eval(html.slice(html.indexOf('    let testDaysRequestId = 0;'),html.indexOf('    function loadVocabDays()')));
w.loadTestDays();el('sheetName').value='수능단어DB';w.loadTestDays();
pending[1].ok([1,2,3]);pending[0].ok([9,10]);
assert.deepEqual(Array.from(el('startDay').options,o=>o.value),['1','2','3']);
assert.equal(el('startButton').disabled,false);
w.loadTestDays();pending[2].fail(new Error('test'));
assert.equal(el('startButton').disabled,true);
w.loadTestDays();pending[3].ok([]);
assert.equal(el('startButton').disabled,true);
console.log('Test setup: grade defaults, manual choices, 30 questions, Day bounds, stale responses and failures passed.');
el('vocabDay').disabled=true;
await new Promise(resolve=>w.setTimeout(resolve,0));
assert.equal(el('hsmPickvocabDay').disabled,true);
el('vocabDay').disabled=false;el('vocabDay').innerHTML='<option value="1">Day 1</option>';
await new Promise(resolve=>w.setTimeout(resolve,0));
assert.equal(el('hsmPickvocabDay').textContent,'Day 1 ⌄');
assert.equal(el('hsmPickvocabDay').disabled,false);
w.close();
