// Real page styles and room module; only API/session fixtures are simulated.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const people=Array.from({length:8},(_,i)=>({id:'p'+i,name:['민준','서연','지우','하준','서윤','도윤','예린','지호'][i],level:8,title:'단어수집가',image:i===0?'./images/emblems/achievement-reborn.png':'./images/emblems/title-chick.png',seat:i,ready:false,score:0,ms:0,online:true,left:false,answered:false}));
const settings={source:'standard',kind:'standard',title:'중등단어DB',start:1,end:5,count:10,mode:'mixed',seconds:10};let room={id:'room1',title:'같이 단어 한 판 할까요?',capacity:8,host:'p0',me:'p0',members:people.slice(0,3),status:'waiting',settings,serverNow:new Date().toISOString(),chat:[],round:0};let messageId=0;const actions=[];
await page.route('**/*',async r=>{const url=new URL(r.request().url());if(url.pathname==='/word-battle'){const {action,payload:p}=r.request().postDataJSON();actions.push(action);let result;if(action==='roomLobby')result={me:people[0],rooms:[{...room,joined:false,host:people[0]},{...room,id:'room2',title:'수능 Day 1~10 도전!',capacity:4,members:people.slice(0,2),host:people[1],locked:true},{...room,id:'room3',title:'불꽃 튀는 8인전',members:people,status:'playing',host:people[2]}]};else if(action==='roomCatalog')result=[{id:'standard',title:'중등단어DB',kind:'standard',days:[1,2,3,4,5]}];else if(action==='roomCreate'){room={...room,title:p.title,capacity:p.capacity,members:[people[0]],status:'waiting'};result=room;}else if(action==='roomReady'){room.members=room.members.map(m=>m.id==='p0'?{...m,ready:p.ready}:m);result=room;}else if(action==='roomChat'){room.chat.push({id:++messageId,sender:'p0',kind:p.kind,body:p.body,at:new Date().toISOString()});result=room;}else if(action==='roomStart'){room={...room,status:'playing',roundAt:new Date(Date.now()+3000).toISOString(),deadline:new Date(Date.now()+13000).toISOString(),question:null};result=room;}else if(action==='roomAnswer'){room.answered=true;room.choice=p.choice;result=room;}else result=room;room.serverNow=new Date().toISOString();return r.fulfill({json:{success:true,result}});}const file=path.join(process.cwd(),'public',url.pathname==='/'?'index.html':url.pathname);if(url.hostname!=='app.test'||!fs.existsSync(file))return r.abort();let data=fs.readFileSync(file);if(file.endsWith('index.html'))data=Buffer.from(data.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''));await r.fulfill({body:data,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':undefined});});
await page.goto('https://app.test/');await page.evaluate(()=>{document.getElementById('appSplash')?.remove();document.getElementById('loginScreen').classList.add('hidden');document.getElementById('mainApp').classList.remove('hidden');document.body.classList.add('hsm-student-app-open');window.currentStudent={studentId:'fixture'};window.hsmEnsureStudentSession_=async()=>'fixture';window.HANSALMAE_CONFIG={apiUrl:'https://app.test/api'};window.hideAllStudentMainScreens_=()=>document.querySelectorAll('#mainApp>.card,#battleRoomScreen').forEach(e=>e.classList.add('hidden'));window.setActiveMenu=()=>{};window.showMyPage=()=>{};window.HSMDialog={confirm:async()=>true};});await page.addScriptTag({path:path.join(process.cwd(),'public/battle-rooms.js')});await page.evaluate(()=>window.hsmOpenFriendBattle_());await page.locator('.br-room-card').first().waitFor();
const overflow=async()=>{const v=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(v.scroll<=v.width+1,JSON.stringify(v));};
for(const width of [320,393,820,1440]){await page.setViewportSize({width,height:1000});await overflow();assert.equal(await page.locator('.br-room-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width<=700?1:2);if(width===1440)await page.screenshot({path:'/tmp/rooms135-lobby.png',fullPage:true});}
await page.locator('[data-br="join"]').first().click();await page.locator('.br-podium').first().waitFor();assert.equal(await page.locator('.br-podium').count(),8);assert.equal(await page.locator('.br-podium.is-occupied').count(),3);await page.waitForTimeout(700);
for(const width of [320,393,820,1440]){await page.setViewportSize({width,height:1000});await overflow();assert.equal(await page.locator('.br-stage').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),4);assert(await page.locator('#brChatMount').evaluate(e=>e.getBoundingClientRect().top>=document.querySelector('.br-stage-card').getBoundingClientRect().bottom));assert(await page.locator('[data-br="ready"]').evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight-69&&r.top>=0&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));if([393,1440].includes(width))await page.screenshot({path:`/tmp/rooms135-waiting-${width}.png`,fullPage:true});}
await page.locator('[data-br="person"]').first().click();await page.locator('.br-person-detail').waitFor();await page.locator('[data-br="dismiss"]').click();await page.locator('[data-br="ready"]').click();await page.waitForFunction(()=>document.querySelector('[data-br="ready"]')?.textContent==='준비 취소');await page.locator('#brChatInput').fill('작성 중인 메시지');await page.locator('#brChatInput').focus();await page.waitForTimeout(2300);assert.equal(await page.locator('#brChatInput').inputValue(),'작성 중인 메시지');await page.locator('[data-br="send"]').click();await page.locator('.br-message p').filter({hasText:'작성 중인 메시지'}).waitFor();assert.equal(await page.locator('[data-br="emoji"]').count(),0);
room.members=people.map(p=>({...p,ready:true}));await page.waitForTimeout(2300);await page.locator('[data-br="start"]').click();await page.locator('.br-intro').waitFor();assert(await page.locator('.br-intro').evaluate(e=>e.classList.contains('br-party')));await page.waitForTimeout(3100);room.question={prompt:'together',mode:'engToKor',options:[{id:'a',text:'함께'},{id:'b',text:'천천히'},{id:'c',text:'언제나'},{id:'d',text:'바로'}],correctId:null};room.roundAt=new Date(Date.now()-1000).toISOString();room.deadline=new Date(Date.now()+9000).toISOString();await page.locator('[data-br="answer"]').first().waitFor();await page.locator('[data-br="answer"]').first().click();assert.equal(await page.locator('[data-br="answer"]:disabled').count(),4);assert(!await page.locator('#brChatInput').count());
for(const width of [320,393,820,1440]){await page.setViewportSize({width,height:1000});await overflow();if(width===393)await page.screenshot({path:'/tmp/rooms135-playing.png',fullPage:true});}
room.status='finished';room.review=[{word:'together',meaning:'함께',correct:false,example:'We learn together.',translation:'우리는 함께 배워요.'}];room.reward={points:5,xp:25};await page.locator('.br-result-card').waitFor();assert.equal(await page.locator('.br-result-row').count(),8);await page.locator('[data-br="leave"]').first().click();await page.locator('[data-br="create"]').first().click();for(const size of [{width:320,height:568},{width:393,height:852},{width:820,height:1180},{width:1440,height:900}]){
 await page.setViewportSize(size);
 await page.evaluate(()=>{let nav=document.getElementById('navOcclusionFixture');if(!nav){nav=document.createElement('div');nav.id='navOcclusionFixture';nav.style.cssText='position:fixed;bottom:0;left:0;right:0;height:100px;z-index:99980;background:white';document.body.append(nav);}});
 await page.locator('[data-br="save"]').scrollIntoViewIfNeeded();
 assert(await page.locator('[data-br="save"]').evaluate(e=>{const r=e.getBoundingClientRect();const top=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.top>=0&&r.bottom<=innerHeight&&e.contains(top);}), 'create button must remain visible above navigation');
 await page.screenshot({path:'/tmp/room-dialog-'+size.width+'.png'});
}
await page.evaluate(()=>document.getElementById('navOcclusionFixture').remove());
await page.locator('#brTitle').fill('함께하는 방');await page.locator('#brCapacity').selectOption('3');await page.locator('[data-br="save"]').click();await page.locator('.br-stage').waitFor();assert.equal(await page.locator('.br-podium').count(),3);assert.equal(await page.locator('.br-podium.is-occupied').count(),1);room.capacity=2;await page.waitForFunction(()=>document.querySelectorAll('.br-podium').length===2);assert.equal(await page.locator('.br-stage').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2);assert.deepEqual(errors,[]);console.log('PASS lobby, responsive 320–1440, 8/3 seat rooms, ready, chat draft, emoji, intro, answer lock, results and create');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
