import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const dom=new JSDOM('<section id="room"></section>',{runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document,root=d.querySelector('#room');
w.eval(readFileSync('public/battle-chat.js','utf8'));
const ui=w.HSMBattleChat,g={id:'room',me:'a',status:'ready',host:{id:'a',name:'나'},guest:{id:'b',name:'친구'},chat:{messages:[],serverNow:new Date().toISOString()}};
let payload,resolveSend;const send=(_,p)=>{payload=p;return new Promise(r=>resolveSend=r);};const warnings=[];
const mount=()=>ui.mount(root,g,send,m=>warnings.push(m));
root.innerHTML='<div class="bc-slot"></div>';mount();
const input=root.querySelector('input');input.value='안녕';input.focus();
root.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.equal(payload.body,'안녕');
input.value='다음 메시지';
g.chat.messages=[{id:2,sender:'b',kind:'text',body:'<img src=x onerror=alert(1)>',at:new Date().toISOString()}];mount();
assert.equal(d.activeElement,input);assert.equal(input.value,'다음 메시지');assert.equal(root.querySelectorAll('.bc-log img').length,0);
resolveSend({messages:[{id:1,sender:'a',kind:'text',body:'안녕',at:new Date().toISOString()}]});await new Promise(r=>setTimeout(r,0));
assert.equal(input.value,'다음 메시지');assert.equal(root.querySelectorAll('.bc-message').length,2);
g.status='playing';root.innerHTML=ui.controls(g)+'<div class="fb-fighter fb-host"></div><div class="fb-fighter fb-guest"></div><button id="answer">정답</button>';mount();
assert.equal(root.querySelectorAll('input').length,0);assert.equal(root.querySelectorAll('[data-chat="emoji"]').length,5);
root.querySelector('.bc-toggle').click();root.querySelector('[data-emoji="💗"]').click();assert.equal(payload.kind,'emoji');assert(!root.querySelector('#answer').disabled);
resolveSend({messages:[{id:3,sender:'a',kind:'emoji',body:'💗',at:new Date().toISOString()}]});await new Promise(r=>setTimeout(r,0));assert.equal(root.querySelector('.fb-host .bc-reaction').textContent,'💗');
g.chat.messages=[{id:4,sender:'b',kind:'emoji',body:'😛',at:new Date().toISOString()}];mount();assert(root.querySelector('.fb-guest .bc-reaction'));
root.querySelector('[data-chat="mute"]').click();assert(!root.querySelector('.fb-guest .bc-reaction'));assert(root.querySelector('.fb-host .bc-reaction'));
g.id='another';mount();assert.equal(root.querySelectorAll('.fb-host .bc-reaction').length,0);
assert.deepEqual(warnings,[]);dom.window.close();console.log('PASS: chat draft/focus, XSS, concurrent response merge, emoji-only live controls, independent answers, mute and room isolation.');
