import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const dom=new JSDOM(html,{runScripts:'outside-only'}), w=dom.window;
w.setTimeout=()=>0;
w.currentLoginToken='test';w.HSMDialog={alert(){}};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
const entries=[{emblemId:'a',emblemName:'보유',owned:true,equipped:false,imagePath:'a.png'},{emblemId:'b',emblemName:'미획득',owned:false,imagePath:'b.png',conditionText:'Lv.15 달성',progressPercent:53},{emblemId:'c',emblemName:'장착',owned:true,equipped:true,imagePath:'c.png'}];
let fail=false,calls=0;
w.google={script:{run:{withSuccessHandler(ok){return{withFailureHandler(bad){return{getStudentEmblems(){ok({success:true,emblems:entries,acquiredCount:2,totalCount:3,equippedEmblem:entries.find(e=>e.equipped)});},equipStudentEmblem(token,id){calls++;if(fail)bad(new Error('재시도'));else ok({success:true});}};}};}}}};
w.eval(w.document.getElementById('hsmEmblemPlugin').textContent);
await w.HSMEmblems.load(true);
assert.equal(w.document.querySelectorAll('.collection-tile').length,3);
assert.equal(w.document.querySelectorAll('.collection-tile:not(.locked) .collection-progress').length,0);
w.HSMEmblems.filter('locked');assert.equal(w.document.querySelectorAll('.collection-tile').length,1);
w.HSMEmblems.showDetail('b');
assert.equal(w.document.querySelector('.collection-detail-image').style.filter,'grayscale(1)');
assert.equal(w.document.querySelector('.collection-detail-image').style.getPropertyPriority('filter'),'important');
assert.equal(w.document.querySelector('.collection-detail-action').disabled,true);
w.HSMEmblems.filter('owned');assert.equal(w.document.querySelectorAll('.collection-tile').length,2);
w.HSMEmblems.showDetail('a');
assert.equal(w.document.querySelector('.collection-detail-image').style.filter,'none');
assert.equal(w.document.querySelector('.collection-detail-image').style.opacity,'1');
fail=true;await w.HSMEmblems.equip('a');
assert.equal(w.document.querySelector('.collection-detail-action').disabled,false);
assert.match(w.document.querySelector('.collection-detail-message').textContent,/재시도/);
fail=false;await Promise.all([w.HSMEmblems.equip('a'),w.HSMEmblems.equip('a')]);assert.equal(calls,2);
assert.equal(w.document.querySelector('.collection-detail-action').disabled,true);
w.document.getElementById('hsmCollectionDetail').close();
w.HSMEmblems.open();assert.equal(w.document.getElementById('hsmEmblemModal').getAttribute('aria-hidden'),'false');
w.HSMEmblems.close();assert.equal(w.document.getElementById('hsmEmblemModal').getAttribute('aria-hidden'),'true');
await new Promise(resolve=>setImmediate(resolve));
// Dictionary is one collectible, with a persisted appearance selected in its detail.
const dictionary={emblemId:'title_dictionary',emblemName:'WALKING DICTIONARY',owned:true,equipped:false,form:'A',imagePath:'./images/emblems/title-dictionary.png'};
entries.push(dictionary);
let savedForm='A',savedId='c',rejectForm=false;
w.google.script.run.withSuccessHandler=ok=>({withFailureHandler:bad=>({
  getStudentEmblems(){
    const emblems=entries.map(e=>({...e,equipped:e.emblemId===savedId,...(e.emblemId==='title_dictionary'?{form:savedForm,imagePath:'./images/emblems/title-dictionary'+(savedForm==='B'?'-b':'')+'.png'}:{})}));
    ok({success:true,emblems,acquiredCount:3,totalCount:4,equippedEmblem:emblems.find(e=>e.equipped)});
  },
  equipStudentEmblem(token,id,form){if(rejectForm)return bad(new Error('저장 실패'));savedId=id;if(form)savedForm=form;ok({success:true});}
})});
await w.HSMEmblems.load(true);w.HSMEmblems.showDetail('title_dictionary');
const choose=form=>w.document.querySelector('[data-form="'+form+'"]').click();
choose('B');assert.match(w.document.querySelector('.collection-detail-image').src,/dictionary-b/);
assert.equal(savedForm,'A','preview does not save');
rejectForm=true;await w.HSMEmblems.equip('title_dictionary','B');
assert.equal(savedForm,'A');assert.equal(w.document.querySelector('[data-form="A"]').disabled,false);
rejectForm=false;await w.HSMEmblems.equip('title_dictionary','B');
assert.equal(savedForm,'B');assert.match(w.document.getElementById('hsmHomeEmblemImage').src,/dictionary-b/);
choose('A');assert.equal(w.document.querySelector('.collection-detail-action').disabled,false);
await w.HSMEmblems.equip('title_dictionary','A');
choose('B');assert.equal(w.document.querySelector('.collection-detail-action').disabled,false,'toggle uses refreshed saved form');
await w.HSMEmblems.equip('title_dictionary','B');
w.HSMEmblems.reset();await w.HSMEmblems.load(true);w.HSMEmblems.showDetail('title_dictionary');
assert.equal(w.document.querySelector('[data-form="B"]').getAttribute('aria-pressed'),'true');
assert.equal(w.document.querySelector('.collection-detail-action').disabled,true);
dictionary.owned=false;await w.HSMEmblems.load(true);w.HSMEmblems.showDetail('title_dictionary');choose('A');
assert.equal(w.document.querySelector('.collection-detail-action').disabled,true,'unowned variants are preview only');
w.document.getElementById('hsmCollectionDetail').close();
// A delayed response from a previous account must not populate the next account.
const pending=[];
w.google.script.run.withSuccessHandler=ok=>({withFailureHandler:bad=>({getStudentEmblems(){pending.push({ok,bad});}})});
w.currentStudent={studentId:'first'};w.currentLoginToken='first-token';
const first=w.HSMEmblems.load(true);
w.currentStudent=null;w.currentLoginToken='';w.HSMEmblems.reset();
assert.equal(w.document.querySelectorAll('.collection-tile').length,0);
assert.equal(w.document.getElementById('hsmHomeEmblemImage').hasAttribute('src'),false);
w.currentStudent={studentId:'second'};w.currentLoginToken='second-token';
const second=w.HSMEmblems.load(true);
assert.equal(pending.length,2,'new account may load while the old request is pending');
pending[1].ok({success:true,emblems:[{...entries[0],emblemName:'새 계정',imagePath:'second.png'}],acquiredCount:1,totalCount:1,equippedEmblem:{emblemName:'새 계정',imagePath:'second.png'}});
await second;
pending[0].ok({success:true,emblems:entries,acquiredCount:2,totalCount:3,equippedEmblem:entries[2]});await first;
assert.equal(w.document.getElementById('hsmHomeEmblemName').textContent,'새 계정');
assert.equal(w.document.querySelectorAll('.collection-tile').length,1);
// Refreshing the token for the same account keeps its cached collection.
w.currentLoginToken='second-renewed';await w.HSMEmblems.load(false);
assert.equal(pending.length,2);
dom.window.close();console.log('PASS collection filters, locked details, equip failure/retry, duplicate guard and modal state');
