import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const source=n=>fs.readFileSync(new URL('../public/'+n,import.meta.url),'utf8');
const dom=new JSDOM('<div id="hsmSchoolStudentPage"><div id="hsmSchoolPageBody"><div class="hsm-school-action-row"><button id="hsmSchoolStartMixed">시험</button></div><div class="hsm-school-word-list">'+['alpha','beta','gamma','delta'].map((word,i)=>`<div class="hsm-school-word-row"><span class="hsm-school-word-num">${i+1}</span><span class="hsm-school-word-eng">${word}</span><span class="hsm-school-word-mean">뜻${i}</span></div>`).join('')+'</div></div></div>',{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window,d=w.document;let frame;w.requestAnimationFrame=cb=>{frame=cb;};w.HSMDialog={alert:(...a)=>w.alert(...a),confirm:async(...a)=>w.confirm(...a),prompt:async(...a)=>w.prompt(...a)};w.alert=()=>assert.fail('native alert must not block validation');w.eval(source('school-vocab-free-test-ui.js'));frame();
const checks=d.querySelectorAll('.hsm-school-word-check');checks[0].checked=true;checks[0].dispatchEvent(new w.Event('change'));checks[1].checked=true;checks[1].dispatchEvent(new w.Event('change'));
const search=d.querySelector('#hsmSchoolWordSearch');search.value='delta';search.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.hsm-school-word-row')[0].style.display,'none');assert.equal(checks[0].checked,true);
const scope=d.querySelector('#hsmSchoolTestScope');scope.value='selected';scope.dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#hsmSchoolTestCount').max,'2');d.querySelector('#hsmSchoolTestCount').value='1';d.querySelector('#hsmSchoolStartNow').click();assert.match(d.querySelector('.question').textContent,/^(alpha|beta|뜻0|뜻1)$/);assert.equal(d.querySelectorAll('[data-answer]').length,4);dom.window.close();
console.log('PASS selected scope only draws selected questions; distractors use full book; search preserves selections');
const statusDom=new JSDOM('<button id="hsmSchoolVocabShortcut"><div class="shortcut-count">不</div></button>',{url:'https://example.test',runScripts:'outside-only'});const s=statusDom.window;s.localStorage.setItem('hansalmaeStudentToken','fixture');s.HANSALMAE_CONFIG={apiUrl:'https://example.test/api'};s.fetch=async()=>({ok:true,json:async()=>({success:true,result:[{wordCount:200}]})});s.eval(source('school-vocab-shortcut-status.js'));s.dispatchEvent(new s.Event('hsm:student-session'));await new Promise(r=>setTimeout(r,20));assert.equal(s.document.querySelector('.shortcut-count').textContent,'배정 단어장 1개 · 단어 200개');statusDom.window.close();console.log('PASS school shortcut refreshes after login');
const html=source('index.html'),render=html.slice(html.indexOf('    function renderVocabulary() {'),html.indexOf('    function getCheckedWords()'));
const cards=new JSDOM('<select id="vocabSheetName"><option>Book</option></select><input id="showCheckedOnly" type="checkbox"><div id="wordList"></div><div id="vocabCount"></div>',{url:'https://example.test',runScripts:'outside-only'});const c=cards.window;c.vocabWords=[{word:'alpha',meaning:'뜻',day:1,example:'Example',translation:'해석'},{word:'beta',meaning:'뜻2',day:1}];c.isWordChecked=()=>false;c.escapeHtml=v=>String(v);c.eval(render);c.renderVocabulary();assert.equal(c.document.querySelectorAll('details').length,1);assert.equal(c.document.querySelector('details').open,false);c.document.querySelector('details').open=true;c.renderVocabulary();assert.equal(c.document.querySelector('details').open,true);assert.match(c.document.querySelector('.word-check').getAttribute('aria-label'),/alpha/);assert.equal(c.document.querySelector('.word-example').textContent,'Example');assert.equal(c.document.querySelector('.word-translation').textContent,'해석');let savedPayload;c.saveToPersonalVocabulary=(item,button)=>{savedPayload={item,button};};
const bookmark=c.document.querySelector('.word-title .word-bookmark');assert.ok(bookmark);assert.equal(bookmark.querySelectorAll('svg').length,1);bookmark.click();assert.equal(savedPayload.item.word,'alpha');assert.equal(savedPayload.button,bookmark);
let saveRequest;c.currentLoginToken='fixture';c.HSMDialog={alert:()=>{}};c.loadPersonalVocabularyPreview=()=>{};
c.google={script:{get run(){return {withSuccessHandler(fn){this.ok=fn;return this;},withFailureHandler(fn){this.fail=fn;return this;},addPersonalVocabularyToBook(){saveRequest=this;}};}}};
c.eval(html.slice(html.indexOf('    function saveItemToSelectedBook('),html.indexOf('    function saveToPersonalVocabulary(',html.indexOf('    function saveItemToSelectedBook('))));
c.saveItemToSelectedBook('book',savedPayload.item,bookmark);saveRequest.fail(new Error('offline'));assert.equal(bookmark.classList.contains('is-saved'),false);
c.saveItemToSelectedBook('book',savedPayload.item,bookmark);saveRequest.ok({success:true});assert.equal(bookmark.classList.contains('is-saved'),true);assert.match(bookmark.getAttribute('aria-label'),/저장 완료/);
cards.window.close();console.log('PASS examples start compact, stay expanded on rerender, and retain original content');
const smart=new JSDOM('<button id="smartReviewStartButton"></button><select id="smartReviewCount"><option>20</option></select><div id="smartReviewLoading"></div><div id="smartReviewList"></div><div id="smartReviewSummary"></div><div id="wrongNotebookSummary"></div>',{url:'https://example.test',runScripts:'outside-only'});const sw=smart.window;const pending=[];sw.smartReviewWords=[{word:'stale'}];sw.currentLoginToken='fixture';sw.renderSmartReview=()=>{};sw.google={script:{get run(){const req={};return {withSuccessHandler(fn){req.ok=fn;return this;},withFailureHandler(fn){req.fail=fn;return this;},getSmartReviewWords(){pending.push(req);},setWrongWordMastered(){pending.push(req);}};}}};sw.eval(html.slice(html.indexOf('    let smartReviewRequestId ='),html.indexOf('    function renderSmartReview()')));sw.loadSmartReview();assert.equal(sw.smartReviewWords.length,0);assert.equal(sw.document.querySelector('button').disabled,true);sw.loadSmartReview();pending[1].ok({words:[1,2,3,4]});pending[0].ok({words:[9]});assert.deepEqual(Array.from(sw.smartReviewWords),[1,2,3,4]);sw.loadSmartReview();pending[2].fail(new Error('offline'));assert.equal(sw.smartReviewWords.length,0);assert.equal(sw.document.querySelector('button').disabled,true);
sw.wrongNotebookWords=[{rowNumber:1,mastered:false}];sw.HSMDialog={alert:(...a)=>sw.alert(...a),confirm:async(...a)=>sw.confirm(...a),prompt:async(...a)=>sw.prompt(...a)};sw.alert=()=>{};sw.renderWrongNotebook=()=>{};sw.loadWrongNotebookPreview=()=>{};sw.eval(html.slice(html.indexOf('    function toggleWrongWordMastered('),html.indexOf('    function updateWrongNotebookSummary_()')));sw.toggleWrongWordMastered(1,true);pending[3].fail(new Error('offline'));assert.equal(sw.wrongNotebookWords[0].mastered,false);sw.toggleWrongWordMastered(1,true);pending[4].ok({success:true});assert.equal(sw.wrongNotebookWords[0].mastered,true);smart.window.close();console.log('PASS stale smart review responses ignored; loading/error blocks old exam; failed mastery save retains prior state');
const screens=new JSDOM('<div id="teacherExamList"></div><div id="studentNotificationList"></div>',{url:'https://example.test',runScripts:'outside-only'}),ew=screens.window;ew.escapeHtml=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');ew.escapeJsString_=x=>String(x);ew.formatTeacherExamDate_=x=>x;ew.teacherAssignedExams=[{examId:'1',title:'예정',availability:'응시대기',status:'미응시'},{examId:'2',title:'진행',availability:'응시가능',status:'시험중'},{examId:'3',title:'완료',availability:'응시불가',status:'응시완료'}];ew.eval(html.slice(html.indexOf('    function renderTeacherExamList_()'),html.indexOf('    async function startAssignedTeacherExam(')));ew.renderTeacherExamList_();const examButtons=ew.document.querySelectorAll('#teacherExamList button');assert.equal(examButtons[0].disabled,true);assert.equal(examButtons[1].disabled,false);assert.equal(examButtons[1].textContent,'이어서 응시');assert.equal(examButtons[2].disabled,true);ew.eval(html.slice(html.indexOf('    function renderStudentNotifications_('),html.indexOf('    function markStudentNotificationRead_(')));ew.renderStudentNotifications_([{notificationId:'1',title:'읽지 않음',read:false},{notificationId:'2',title:'읽음',read:true}]);assert.equal(ew.document.querySelectorAll('.notification-unread').length,1);assert.equal(ew.document.querySelectorAll('.danger-button').length,1);ew.renderStudentNotifications_([]);assert.match(ew.document.querySelector('#studentNotificationList').textContent,/새로운 알림이 없습니다/);screens.window.close();console.log('PASS exam availability/resume buttons and notification unread/delete/empty states');
const routes=new JSDOM('',{url:'https://example.test',runScripts:'outside-only'}),rw=routes.window;const opened=[];rw.hideHsmLauncher_=()=>opened.push('hide');rw.showMyPage=()=>opened.push('mypage');rw.hsmOpenSchoolVocabPage_=()=>opened.push('schoolVocab');rw.hsmOpenSchoolContentPage_=()=>opened.push('schoolContent');const routeStart=html.indexOf('  window.hsmLauncherOpenFeature_ = function (feature) {');rw.eval(html.slice(routeStart,html.indexOf('  const previousOpenMainApp',routeStart)));rw.hsmLauncherOpenFeature_('schoolVocab');assert.deepEqual(opened,['hide','mypage','schoolVocab']);opened.length=0;rw.hsmLauncherOpenFeature_('schoolContent');assert.deepEqual(opened,['hide','mypage','schoolContent']);routes.window.close();console.log('PASS school home shortcuts preserve learning page as return destination');
const idle=new JSDOM('<div id="hsmSchoolStudentPage"><div id="hsmSchoolPageBody"><div class="hsm-school-action-row"><button id="hsmSchoolStartMixed">시험</button></div><div class="hsm-school-word-list">'+['alpha','alpha','beta','gamma'].map(word=>`<div class="hsm-school-word-row"><span class="hsm-school-word-num">1</span><span class="hsm-school-word-eng">${word}</span><span class="hsm-school-word-mean">뜻${word}</span></div>`).join('')+'</div></div></div>',{url:'https://example.test',runScripts:'outside-only'});const iw=idle.window;let updates=0,closed=false;const timers=[];iw.requestAnimationFrame=cb=>{if(closed)return;updates++;if(updates<80)timers.push(setTimeout(cb,1));};iw.eval(source('school-vocab-free-test-ui.js'));iw.eval(source('school-vocab-selection-fix.js'));await new Promise(r=>setTimeout(r,150));const settled=updates;await new Promise(r=>setTimeout(r,80));assert.equal(updates,settled,'idle observers must stop');assert.ok(updates<20);assert.equal(iw.document.querySelector('#hsmSchoolAddPersonal').hidden,true);const first=iw.document.querySelector('.hsm-school-word-check');first.checked=true;first.dispatchEvent(new iw.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));assert.equal(iw.document.querySelector('#hsmSchoolSelectedCount').textContent,'2개 선택');assert.equal(iw.document.querySelector('#hsmSchoolAddPersonal').hidden,false);const settledSelected=updates;await new Promise(r=>setTimeout(r,80));assert.equal(updates,settledSelected,'duplicate words must not cause count oscillation');closed=true;timers.forEach(clearTimeout);idle.window.close();console.log('PASS idle observers settle; duplicate selections stay consistent; save action appears only on selection');


const consistencyHtml=source('index.html');
const selectionHintDom=new JSDOM('<p id="personalTestSelectionHint"></p>',{url:'https://example.test',runScripts:'outside-only'});
const sh=selectionHintDom.window;let selectedForHint=[],startedForHint=0;
sh.personalVocabularyWords=[1,2,3,4].map(rowNumber=>({rowNumber}));
sh.getSelectedPersonalRows_=()=>selectedForHint;
sh.personalSelectionMode_=false;
sh.applyPersonalSelectionMode_=()=>sh.updatePersonalTestHint_();
sh.showPersonalTestSetup=()=>{startedForHint++;};
sh.HSMDialog={alert:(...a)=>sh.alert(...a),confirm:async(...a)=>sh.confirm(...a),prompt:async(...a)=>sh.prompt(...a)};sh.alert=()=>assert.fail('selection validation must use an inline hint');
sh.eval(consistencyHtml.match(/function updatePersonalTestHint_\(\) \{[\s\S]*?(?=\n    function togglePersonalSelectionMode_)/)[0]);
sh.eval(consistencyHtml.match(/<script id="hsm-personal-test-selection-helper">([\s\S]*?)<\/script>/)[1]);
sh.showPersonalTestSetup();assert.equal(startedForHint,0);assert.equal(sh.personalSelectionMode_,true);
assert.match(sh.document.querySelector('p').textContent,/4개 더 선택/);
selectedForHint=[1,2];sh.showPersonalTestSetup();assert.match(sh.document.querySelector('p').textContent,/2개 더 선택/);
sh.personalVocabularyWords=[{rowNumber:1},{rowNumber:2}];sh.updatePersonalTestHint_();assert.match(sh.document.querySelector('p').textContent,/시험은 단어 4개부터/);
sh.personalVocabularyWords=[1,2,3,4].map(rowNumber=>({rowNumber}));selectedForHint=[1,2,3,4];sh.updatePersonalTestHint_();
assert.equal(sh.document.querySelector('p').classList.contains('is-ready'),true);
sh.showPersonalTestSetup();assert.equal(startedForHint,1);selectionHintDom.window.close();
console.log('PASS personal test validation stays inline and requires four valid selected words');

const coverLifecycleDom=new JSDOM('<div id="vocabScreen"><div id="wordList"><div class="word-card"><div class="word-English">test</div><div class="word-meaning">시험</div></div></div></div>',{url:'https://example.test',runScripts:'outside-only'});
const cl=coverLifecycleDom.window;let coverFrame;
cl.requestAnimationFrame=fn=>{coverFrame=fn;};
cl.eval(source('word-cover.js'));cl.document.dispatchEvent(new cl.Event('DOMContentLoaded'));
const coverMeaning=cl.document.querySelector('.word-meaning');
cl.document.querySelector('[data-cover-mode="meaning"]').click();
assert.equal(coverMeaning.getAttribute('role'),'button');
coverMeaning.click();assert.equal(coverMeaning.getAttribute('aria-pressed'),'true');
if(coverFrame)coverFrame();assert.equal(coverMeaning.getAttribute('aria-pressed'),'true');
cl.document.querySelector('[data-cover-mode="off"]').click();
for(const attr of ['role','tabindex','aria-label','aria-pressed'])assert.equal(coverMeaning.hasAttribute(attr),false);
coverMeaning.click();assert.equal(coverMeaning.classList.contains('hsm-cover-revealed'),false);
cl.document.querySelector('[data-cover-mode="meaning"]').click();
assert.equal(coverMeaning.getAttribute('tabindex'),'0');
coverMeaning.dispatchEvent(new cl.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal(coverMeaning.getAttribute('aria-pressed'),'true');coverLifecycleDom.window.close();
console.log('PASS cover off restores plain text; reactivation keeps keyboard reveal working');


// Personal selection: controls follow selection, exit clears checks, and refresh preserves them.
const personalMarkup=html.slice(html.indexOf('      <!-- 나만의 단어장 화면 -->'),html.indexOf('      <!-- 나만의 단어장 시험 설정 -->'));
const personalDom=new JSDOM(personalMarkup,{url:'https://example.test',runScripts:'outside-only'});
const pw=personalDom.window,pd=pw.document;
pw.personalSelectionMode_=false;pw.selectedPersonalBookId='one';
pw.personalVocabularyBooks=[{bookId:'one',bookName:'Book'}];
pw.personalVocabularyWords=[1,2,3,4,5].map(rowNumber=>({rowNumber,word:'word'+rowNumber,meaning:'meaning'}));
pw.escapeHtml=value=>String(value);
pw.eval(html.slice(html.indexOf('    function getSelectedPersonalRows_()'),html.indexOf('    function moveSelectedPersonalWords_()')));
pw.eval(html.slice(html.indexOf('  function renderPersonalVocabulary()'),html.indexOf('  function showPersonalTestSetup()',html.indexOf('  function renderPersonalVocabulary()'))));
pw.renderPersonalVocabulary();
assert.equal(pd.querySelector('#personalBulkToolbar').classList.contains('hidden'),true);
pw.togglePersonalSelectionMode_();
assert.equal(pd.querySelector('#personalSelectionModeButton').getAttribute('aria-expanded'),'true');
assert.equal(pd.querySelector('#personalTestButton').disabled,true);
assert.equal(pd.querySelector('#personalSelectionActions').classList.contains('hidden'),true);
pw.toggleSmartPersonalSelectAll_();
assert.equal(pd.querySelector('#personalSelectedCount').textContent,'5');
assert.equal(pd.querySelector('#personalTestButton').disabled,false);
assert.equal(pd.querySelector('#personalSelectionActions').classList.contains('hidden'),false);
assert.equal(pd.querySelectorAll('.personal-item.is-selected').length,5);
pw.renderPersonalVocabulary();
assert.equal(pd.querySelectorAll('.personal-share-check:checked').length,5);
pw.toggleSmartPersonalSelectAll_();
assert.equal(pd.querySelector('#personalSelectedCount').textContent,'0');
assert.equal(pd.querySelector('#personalSelectionActions').classList.contains('hidden'),true);
pw.toggleSmartPersonalSelectAll_();pw.togglePersonalSelectionMode_();
assert.equal(pd.querySelectorAll('.personal-share-check:checked').length,0);
assert.equal(pd.querySelector('#personalSelectionModeButton').getAttribute('aria-expanded'),'false');
pw.personalVocabularyWords=[];pw.renderPersonalVocabulary();
assert.equal(pd.querySelector('#personalSelectedCount').textContent,'0');
assert.equal(pd.querySelector('#personalTestButton').disabled,true);
personalDom.window.close();
console.log('PASS personal selection actions, select all/clear, refresh, exit and empty book');

// Reproduce the mobile column rule that previously stretched the selection bar.
const personalStyleDom=new JSDOM('<style>.personal-toolbar{display:flex;flex-direction:column}.hsm-icon-label{justify-content:center}</style><style>'+source('student-ui.css')+'</style><main id="mainApp">'+personalMarkup+'</main>',{url:'https://example.test'});
const psw=personalStyleDom.window,psd=psw.document;
const barStyle=psw.getComputedStyle(psd.querySelector('.personal-main-toolbar'));
assert.equal(barStyle.flexDirection,'row');
assert.equal(barStyle.flexWrap,'nowrap');
assert.equal(barStyle.minHeight,'44px');
assert.equal(psw.getComputedStyle(psd.querySelector('.personal-selection-panel')).borderTopWidth,'0px');
const menuButton=psd.querySelector('.book-action-row button');menuButton.classList.add('hsm-icon-label');
assert.equal(psw.getComputedStyle(menuButton).justifyContent,'flex-start');
assert.equal(psw.getComputedStyle(menuButton).marginTop,'0px');
assert.equal(psw.getComputedStyle(psd.querySelector('.book-action-row')).width,'164px');
personalStyleDom.window.close();
console.log('PASS personal mobile toolbar stays horizontal; compact menu alignment and spacing');

const bd=new JSDOM('<select id="personalBookSelect"></select><button id="personalBookPickerButton"><span></span></button>',{url:'https://example.test',runScripts:'outside-only'});
const bw=bd.window;let calls=[],nextError=null,changes=0;
bw.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
bw.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new bw.Event('close'));};
bw.personalVocabularyBooks=[{bookId:'one',bookName:'Book <one>',wordCount:2},{bookId:'two',bookName:'Book two',wordCount:5}];
bw.selectedPersonalBookId='one';bw.currentLoginToken='fixture';
bw.renderPersonalBookSelect=function(){const sel=bw.document.querySelector('select');sel.replaceChildren();bw.personalVocabularyBooks.forEach(b=>{const o=bw.document.createElement('option');o.value=b.bookId;o.textContent=b.bookName;o.selected=b.bookId===bw.selectedPersonalBookId;sel.append(o);});};
bw.changePersonalBook=()=>{changes++;bw.selectedPersonalBookId=bw.document.querySelector('select').value;};
bw.loadPersonalBooks=cb=>{bw.renderPersonalBookSelect();if(cb)cb();};bw.loadSelectedPersonalBookWords=()=>{};bw.loadPersonalVocabularyPreview=()=>{};
bw.google={script:{get run(){let ok,fail;const r={withSuccessHandler(f){ok=f;return r;},withFailureHandler(f){fail=f;return r;}};for(const method of ['createVocabularyBook','renameVocabularyBook','deleteVocabularyBook'])r[method]=(...args)=>{calls.push({method,args});Promise.resolve().then(()=>{if(nextError){const e=nextError;nextError=null;fail(e);}else ok({book:{bookId:'two'}});});};return r;}}};
bw.eval(source('personal-dialogs.js'));bw.renderPersonalBookSelect();
bw.openPersonalBookChoice();let dialog=bw.document.querySelector('dialog');
assert.equal(dialog.querySelectorAll('.book-dialog-option').length,2);assert.equal(dialog.querySelector('.book-dialog-option span').textContent,'Book <one>');
dialog.querySelectorAll('.book-dialog-option')[1].click();assert.equal(changes,1);assert.equal(bw.selectedPersonalBookId,'two');assert.equal(dialog.open,false);
bw.createNewPersonalBook();dialog.querySelector('[data-cancel]').click();assert.equal(calls.length,0);
bw.createNewPersonalBook();const submit=()=>dialog.querySelector('form').dispatchEvent(new bw.Event('submit',{cancelable:true}));
submit();assert.equal(calls.length,0);assert.equal(dialog.querySelector('.book-dialog-error').hidden,false);
dialog.querySelector('input').value='  New book  ';submit();submit();assert.equal(calls.length,1);assert.equal(calls[0].args[1],'New book');await new Promise(r=>setTimeout(r,0));assert.equal(dialog.open,false);
bw.renameCurrentPersonalBook();assert.equal(dialog.querySelector('input').value,'Book two');nextError={message:'Try again'};dialog.querySelector('input').value='Rename';submit();await new Promise(r=>setTimeout(r,0));assert.equal(dialog.open,true);assert.equal(dialog.querySelector('.book-dialog-error').textContent,'Try again');assert.equal(dialog.querySelector('input').disabled,false);dialog.querySelector('[data-cancel]').click();
bw.deleteCurrentPersonalBook();assert.match(dialog.querySelector('.book-dialog-description').textContent,/5개/);const beforeDelete=calls.length;dialog.querySelector('[data-cancel]').click();assert.equal(calls.length,beforeDelete);
bw.deleteCurrentPersonalBook();submit();await new Promise(r=>setTimeout(r,0));assert.equal(calls.at(-1).method,'deleteVocabularyBook');assert.equal(calls.at(-1).args[1],'two');assert.equal(dialog.open,false);
bd.window.close();console.log('PASS custom book choice, safe text, cancel, validation, duplicate submit, retry and delete confirmation');
