import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {buildQuestions} from '../supabase/functions/word-battle/questions.mts';
const rows=Array.from({length:30},(_,i)=>({word:'word'+i,meaning:'뜻'+i,example:'Example '+i,translation:'예문'+i}));
for(const count of [10,20,30])for(const mode of ['engToKor','korToEng','mixed']){const qs=buildQuestions(rows,mode,count);assert.equal(qs.length,count);assert.equal(new Set(qs.map(q=>q.word)).size,count);for(const q of qs){assert.equal(q.options.length,4);assert.equal(new Set(q.options.map(o=>o.text)).size,4);assert.equal(q.options.find(o=>o.id===q.correctId).text,q.mode==='engToKor'?q.meaning:q.word);}if(mode==='mixed')assert.equal(qs.filter(q=>q.mode==='engToKor').length,count/2);}
assert.throws(()=>buildQuestions(rows,'mixed',15));assert.throws(()=>buildQuestions(rows.slice(0,20),'mixed',30));
assert.throws(()=>buildQuestions(rows.slice(0,5),'mixed'));assert.throws(()=>buildQuestions(rows,'example'));
for(let i=0;i<10;i++)assert(!buildQuestions([...rows,{word:'word0',meaning:'다른 뜻'}],'engToKor').some(q=>q.word==='word0'));
const dom=new JSDOM('<div id="mainApp"><div id="myPageScreen"><div class="learning-shortcuts"></div></div></div><nav id="hsmMobileNav"><button id="testMenuButton">테스트</button></nav>',{url:'https://example.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;w.scrollTo=()=>{};w.currentStudent={studentId:'test'};w.hsmEnsureStudentSession_=async()=> 'token';w.HANSALMAE_CONFIG={apiUrl:'https://example.test/api'};w.hideAllStudentMainScreens_=()=>d.getElementById('myPageScreen').classList.add('hidden');w.setActiveMenu=()=>{};w.HSMDialog={confirm:async()=>true};w.showMyPage=()=>{};
const me={id:'me',name:'나',level:8,title:'단어수집가'},friend={id:'friend',name:'<img src=x onerror=alert(1)>',level:7,title:'단어수집가',online:true,status:'accepted'},home={me,friends:[friend],blocked:[],battles:[]};
let game={id:'room',status:'invited',settings:{title:'중등단어',kind:'standard',start:1,end:70,mode:'mixed'},me:'me',host:me,guest:friend,hostScore:0,guestScore:0,hostMs:0,guestMs:0,serverNow:new Date().toISOString(),round:0},calls=[];
w.fetch=async(url,args)=>{const body=JSON.parse(args.body);calls.push(body);let result=home;switch(body.action){case 'rewardPreview':result={remaining:70,pairRemaining:2};break;case 'catalog':result=[{id:'middle',title:'중등단어DB',kind:'standard',days:Array.from({length:70},(_,i)=>i+1)}];break;case 'invite':game={...game,settings:{...game.settings,count:body.payload.count,seconds:body.payload.seconds}};result=game;break;case 'poll':result=game;break;case 'ready':game={...game,status:'playing',hostReady:true,guestReady:true,roundAt:new Date(Date.now()+3000).toISOString(),deadline:new Date(Date.now()+13000).toISOString()};result=game;break;case 'answer':game={...game,answered:true,choice:body.payload.choice};result=game;break;case 'leave':result={...game,status:'finished'};break;}return {ok:true,json:async()=>({success:true,result})};};
w.eval(readFileSync('public/friend-battle.js','utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));
const wait=()=>new Promise(r=>setTimeout(r,20)),click=async(sel)=>{assert(d.querySelector(sel),sel);d.querySelector(sel).click();await wait();};
await w.hsmOpenFriendBattle_();assert(d.getElementById('friendBattleScreen').textContent.includes('WORDBATTLE'));assert(!d.querySelector('[onerror]'));
assert(!d.querySelector('#fbAddFriend').open);
await click('[data-action="toggleSearch"]');assert(d.querySelector('#fbAddFriend').open);assert.equal(d.activeElement.id,'fbStudentId');assert.equal(d.querySelector('[data-action="toggleSearch"]').getAttribute('aria-expanded'),'true');
await click('[data-action="toggleSearch"]');assert(!d.querySelector('#fbAddFriend').open);
await click('[data-action="challenge"]');assert.equal(d.querySelector('#fbEnd').options.length,70);assert.equal(d.querySelector('#fbEnd').value,'70');assert(d.querySelector('[aria-label="닫기"]'));
assert.equal(d.querySelector('[data-action="count"][aria-pressed="true"]').dataset.id,'10');
await click('[data-action="count"][data-id="20"]');assert.equal(d.querySelector('[data-action="count"][aria-pressed="true"]').dataset.id,'20');
await click('[data-action="count"][data-id="30"]');assert(d.getElementById('fbRewardPreview').textContent.includes('WIN +15P'));assert(d.getElementById('fbRewardPreview').textContent.includes('70문제'));
assert.equal(d.querySelector('#fbSource').selectedOptions[0].textContent,'중등단어');
await click('[data-action="seconds"][data-id="15"]');
await click('[data-action="seconds"][data-id="20"]');
await click('[data-action="mode"][data-id="korToEng"]');
await click('[data-action="day"][data-id="fbStart"]');assert.equal(d.querySelectorAll('[data-action="pickDay"]').length,70);
await click('[data-action="pickDay"][data-id="70"]');assert.equal(d.querySelector('#fbStart').value,'70');
await click('[data-action="day"][data-id="fbEnd"]');await click('[data-action="pickDay"][data-id="65"]');assert.equal(d.querySelector('#fbStart').value,'65');assert.equal(d.querySelector('#fbEnd').value,'65');
assert.equal(d.querySelector('[data-action="seconds"][aria-pressed="true"]').dataset.id,'20');
await click('[data-action="day"][data-id="fbStart"]');await click('[data-action="dayBack"]');assert(d.querySelector('#fbChallenge'));

await click('[data-action="invite"]');assert.equal(calls.find(c=>c.action==='invite').payload.count,30);assert.equal(calls.find(c=>c.action==='invite').payload.seconds,20);assert.equal(calls.find(c=>c.action==='invite').payload.mode,'korToEng');assert(d.querySelector('.fb-sub').textContent.includes('20초'));assert(d.querySelector('.fb-sub').textContent.includes('30문제'));assert(!d.querySelector('.fb-overlay'));assert(d.getElementById('friendBattleScreen').textContent.includes('친구의 수락'));
game.status='ready';await w.hsmOpenFriendBattle_();await click('[data-action="ready"]');assert(d.getElementById('fbCountdown'));assert.equal(d.querySelectorAll('.fb-option').length,0);
game={...game,roundAt:new Date(Date.now()-1000).toISOString(),question:{prompt:'appearance',mode:'engToKor',correctId:null,options:[{id:'one',text:'외모'},{id:'two',text:'삶'},{id:'three',text:'성장'},{id:'four',text:'요청'}]}};
await w.hsmOpenFriendBattle_();assert(d.querySelector('.fb-round').textContent.includes('01 / 30'));assert.equal(d.querySelectorAll('.fb-option').length,4);assert(!d.querySelector('.is-correct'));
await click('[data-action="answer"]');assert(d.querySelector('.is-picked'));assert([...d.querySelectorAll('.fb-option')].every(b=>b.disabled));assert(!d.querySelector('.is-correct'));assert.equal(calls.filter(c=>c.action==='answer').length,1);
assert(d.querySelector('.is-picked [aria-label="선택 완료"]'));assert(d.querySelector('.fb-host small').textContent.includes('선택 완료'));
game={...game,deadline:new Date(Date.now()+2000).toISOString(),opponentAnswered:true};await w.hsmOpenFriendBattle_();assert(d.querySelector('#fbTimer.is-urgent'));assert(d.querySelector('#fbTimeFill.is-urgent'));assert(d.querySelector('.fb-guest small').textContent.includes('선택 완료'));
game={...game,hostScore:1,revealUntil:new Date(Date.now()+2000).toISOString(),question:{...game.question,correctId:'one'}};await w.hsmOpenFriendBattle_();assert(d.querySelector('.is-correct'));assert(d.querySelector('.fb-score-gain'));assert.equal(d.querySelector('#fbTimer').textContent,'정답 확인');
game={...game,status:'finished',reward:{points:15,xp:55,eligibleCount:30,reason:'awarded',totalBefore:145,totalXp:200,level:3,previousLevel:2,title:'단어수집가',nextLevelXp:300,progress:50},winner:'me',hostScore:10,hostMs:42000,review:[{word:'word',meaning:'뜻',example:'Example',translation:'예문',correct:false}]};await w.hsmOpenFriendBattle_();assert(d.querySelector('.fb-result-heading').textContent.includes('WIN'));assert(d.querySelector('.fb-result-stats').textContent.includes('/ 30'));assert(d.querySelector('.fb-review').textContent.includes('Example'));assert(d.querySelector('.fb-rewards').textContent.includes('+15P'));assert(d.querySelector('.fb-rewards').textContent.includes('+55EXP'));assert.equal(d.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'),'50');game={...game,winner:'friend',guestScore:10,guestMs:41000,review:[],reward:null,rewardsEnabled:false};await w.hsmOpenFriendBattle_();assert(d.querySelector('.fb-result-heading').textContent.includes('LOSE'));assert(d.querySelector('.fb-result-heading').textContent.includes('1.0초 차이'));assert(d.querySelector('.fb-review-clear'));assert(d.querySelector('.fb-reward-note').textContent.includes('적용 전'));assert(!d.querySelector('.fb-review'));
game={...game,winner:null,guestMs:42000};await w.hsmOpenFriendBattle_();assert(d.querySelector('.fb-result-heading').textContent.includes('DRAW'));
game={...game,winner:'friend',reason:'중도 포기로 종료됐어요.'};await w.hsmOpenFriendBattle_();assert(d.querySelector('.fb-result-heading').textContent.includes('중도 포기'));assert(!d.querySelector('.fb-result-heading').textContent.includes('차이'));
await click('[data-action="exit"]');assert(d.getElementById('fbSearch'));assert(!d.getElementById('friendBattleScreen').classList.contains('fb-finished'));
await click('#testMenuButton');assert(d.getElementById('friendBattleScreen').classList.contains('hidden'));
dom.window.close();console.log('PASS: modes, ambiguity, unique options; friends, 70 Days, modal, countdown, answer locking, review, navigation, escaping.');
