import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const dom=new JSDOM(html,{runScripts:'outside-only'}), w=dom.window;
w.setTimeout=()=>0;
w.currentLoginToken='test';w.HSMDialog={alert(){}};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
const entries=[{emblemId:'a',emblemName:'보유',owned:true,equipped:false,imagePath:'a.png'},{emblemId:'b',emblemName:'미획득',owned:false,imagePath:'b.png',conditionText:'Lv.15 달성',progressPercent:53},{emblemId:'c',emblemName:'장착',owned:true,equipped:true,imagePath:'c.png'}];
let fail=false,calls=0;
w.google={script:{run:{withSuccessHandler(ok){return{withFailureHandler(bad){return{getStudentEmblems(){ok({success:true,emblems:entries,acquiredCount:2,totalCount:3,equippedEmblem:entries.find(e=>e.equipped)});},equipStudentEmblem(token,id){calls++;if(fail)bad(new Error('재시도'));else ok({success:true});}};}};}}}};
w.eval(w.document.getElementById('hsmEmblemPlugin').textContent);
await w.HSMEmblems.load(true);
assert.equal(w.document.querySelectorAll('.collection-tile').length,3);
assert.equal(w.document.querySelectorAll('.collection-tile:not(.locked) .collection-progress').length,0);
w.HSMEmblems.filter('locked');assert.equal(w.document.querySelectorAll('.collection-tile').length,1);
w.HSMEmblems.showDetail('b');assert.equal(w.document.querySelector('.collection-detail-action').disabled,true);
w.HSMEmblems.filter('owned');assert.equal(w.document.querySelectorAll('.collection-tile').length,2);
w.HSMEmblems.showDetail('a');fail=true;await w.HSMEmblems.equip('a');
assert.equal(w.document.querySelector('.collection-detail-action').disabled,false);
assert.match(w.document.querySelector('.collection-detail-message').textContent,/재시도/);
fail=false;await Promise.all([w.HSMEmblems.equip('a'),w.HSMEmblems.equip('a')]);assert.equal(calls,2);
assert.equal(w.document.querySelector('.collection-detail-action').disabled,true);
w.document.getElementById('hsmCollectionDetail').close();
w.HSMEmblems.open();assert.equal(w.document.getElementById('hsmEmblemModal').getAttribute('aria-hidden'),'false');
w.HSMEmblems.close();assert.equal(w.document.getElementById('hsmEmblemModal').getAttribute('aria-hidden'),'true');
dom.window.close();console.log('PASS collection filters, locked details, equip failure/retry, duplicate guard and modal state');
