import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const read=n=>fs.readFileSync(new URL('../public/'+n,import.meta.url),'utf8');
const dom=new JSDOM('<body class="hsm-student-app-open"><div class="container"><div id="mainApp"><div id="vocabScreen">단어</div></div></div><nav id="hsmMobileNav"><button id="home">홈</button></nav></body>',{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window,d=w.document;
const media={matches:true,addEventListener(_,f){this.change=f}};
w.matchMedia=()=>media;let nativeCalls=[],position=80;
Object.defineProperty(w,'scrollY',{get:()=>position});
w.scrollTo=(x,y)=>{nativeCalls.push([x,y]);position=typeof x==='object'?x.top:y};
w.HTMLElement.prototype.scrollTo=function(x,y){this.scrollTop=typeof x==='object'?x.top:y};
let clicks=0;d.getElementById('home').onclick=()=>clicks++;
w.eval(read('mobile-app-shell.js'));
const scroll=d.getElementById('hsmMobileAppScroll'),shell=d.getElementById('hsmMobileAppShell'),nav=d.getElementById('hsmMobileNav');
assert.equal(scroll.parentElement,shell);assert.equal(nav.parentElement,shell);assert.equal(scroll.contains(nav),false);
assert.equal(scroll.querySelector('#vocabScreen').textContent,'단어');
assert.equal(w.scrollY,0);assert.equal(scroll.scrollTop,80);assert.equal(w.hsmGetPageScrollY_(),80);
w.scrollTo(0,700);assert.equal(scroll.scrollTop,700);assert.equal(w.scrollY,0);
w.scrollTo({top:0,behavior:'smooth'});assert.equal(scroll.scrollTop,0);
d.getElementById('home').click();assert.equal(clicks,1);
const style=d.createElement('style');style.textContent=read('mobile-app-shell.css').replace('@media(max-width:650px) {','').replace(/}\s*$/,'');d.head.append(style);
assert.equal(w.getComputedStyle(d.body).overflow,'hidden');assert.equal(w.getComputedStyle(shell).display,'grid');assert.equal(w.getComputedStyle(scroll).overflowY,'auto');assert.equal(w.getComputedStyle(nav).position,'relative');
scroll.scrollTop=250;media.matches=false;media.change();assert.equal(d.documentElement.classList.contains('hsm-mobile-shell-active'),false);assert.equal(w.scrollY,250);
w.scrollTo(0,75);assert.equal(w.scrollY,75);
media.matches=true;media.change();assert.equal(scroll.scrollTop,75);assert.equal(w.scrollY,0);
d.body.classList.remove('hsm-student-app-open');await new Promise(r=>setTimeout(r,0));assert.equal(d.documentElement.classList.contains('hsm-mobile-shell-active'),false);
w.eval(read('mobile-app-shell.js'));assert.equal(d.querySelectorAll('#hsmMobileAppShell').length,1);
w.close();console.log('PASS mobile shell: menu outside scroller, document locked, scroll reset/restore, menu events, desktop/logout recovery and idempotent boot');
