import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const html=fs.readFileSync(new URL('../public/teacher.html',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window,d=w.document;
const fn=name=>{const start=html.indexOf('    function '+name+'(');assert.ok(start>=0);const end=html.slice(start+1).search(/\n    (?:async )?function /);return html.slice(start,end<0?html.indexOf('</script>',start):start+1+end);};
w.eval(`var $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));var selectedStudentIds=new Set();var setupData={students:[{studentId:'a',studentName:'Alpha',grade:'고1'},{studentId:'b',studentName:'Beta',grade:'고2'}]};`);
for(const name of ['escapeHtml','renderStudents','updateSelectedCount','selectAllVisibleStudents','clearAllStudents','getPayload'])w.eval(fn(name));
const search=value=>{d.querySelector('#studentSearch').value=value;w.renderStudents();};
const count=value=>assert.equal(d.querySelector('#selectedCount').textContent,value+'명 선택');
search('Alpha');d.querySelector('.student-check').click();count(1);
search('missing');count(1);assert.deepEqual(Array.from(w.getPayload().targetStudentIds),['a']);
search('Beta');w.selectAllVisibleStudents();count(2);assert.deepEqual(Array.from(w.getPayload().targetStudentIds),['a','b']);
search('Alpha');assert.equal(d.querySelector('.student-check').checked,true);assert.match(d.querySelector('.student-check').getAttribute('aria-label'),/Alpha/);
d.querySelector('.student-check').click();count(1);assert.deepEqual(Array.from(w.getPayload().targetStudentIds),['b']);
d.querySelector('#targetType').value='전체';w.updateSelectedCount();count(2);assert.equal(w.getPayload().targetStudentIds.length,0);
d.querySelector('#targetType').value='학생선택';w.updateSelectedCount();count(1);
search('missing');w.clearAllStudents();count(0);search('');assert.equal(d.querySelectorAll(':checked.student-check').length,0);
dom.window.close();console.log('PASS teacher selection survives search, accumulates across results, updates payload and clears hidden selections');
