import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const dom=new JSDOM('<div id="vocabScreen"><div id="vocabCount"></div><label class="filter-check"><input id="showCheckedOnly" type="checkbox"><span></span></label><div class="vocab-actions"><button></button><button></button><button></button></div></div>',{url:'https://example.com',runScripts:'outside-only'});
const w=dom.window,d=w.document;
w.vocabWords=[{word:'one'},{word:'two'}];w.scope='Day1';
w.getCheckStorageKey=x=>w.scope+':'+x.word;
w.getCheckedWords=()=>w.vocabWords.filter(x=>w.localStorage.getItem(w.getCheckStorageKey(x))==='true');
w.renderVocabulary=()=>{};w.loadVocabulary=()=>{};
w.eval(readFileSync('public/vocab-selection.js','utf8'));
d.dispatchEvent(new w.Event('DOMContentLoaded'));
const click=id=>d.getElementById(id).click();
assert.equal(d.querySelector('.vocab-actions').hidden,true);
click('hsmVocabSelect');assert.equal(d.getElementById('hsmVocabSelectionBar').hidden,false);
assert.equal(d.getElementById('hsmVocabSelectAll').textContent,'전체 선택');
click('hsmVocabSelectAll');assert.equal(w.getCheckedWords().length,2);
assert.equal(d.querySelector('.vocab-actions').hidden,false);
assert.equal(d.getElementById('hsmVocabSelectAll').textContent,'전체 해제');
d.getElementById('showCheckedOnly').checked=true;
click('hsmVocabSelectAll');assert.equal(w.getCheckedWords().length,0);
assert.equal(d.getElementById('showCheckedOnly').checked,false);
assert.equal(d.querySelector('.vocab-actions').hidden,true);
click('hsmVocabSelectAll');click('hsmVocabSelectCancel');
assert.equal(w.getCheckedWords().length,2);assert.equal(d.getElementById('hsmVocabSelectionBar').hidden,true);
w.scope='Day2';w.loadVocabulary();w.vocabWords=[{word:'three'}];w.renderVocabulary();
click('hsmVocabSelect');click('hsmVocabSelectAll');
assert.equal(w.localStorage.getItem('Day2:three'),'true');
assert.equal(w.localStorage.getItem('Day1:one'),'true');
assert.equal(d.getElementById('hsmVocabSelectedCount').textContent,'1');
console.log('PASS selection visibility, select/clear toggle, zero selection filter reset, cancel preserves checks, Day isolation');
dom.window.close();
