-- 운영 보강: 관리자 로그인 잠금, 비밀번호 변경 감사, 월간 랭킹 자동 기록
create table if not exists public.admin_login_attempts (
  key_hash text primary key,
  attempts integer not null default 0,
  locked_until timestamptz,
  last_attempt_at timestamptz not null default now()
);

alter table public.admin_login_attempts enable row level security;

create table if not exists public.password_change_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  change_type text not null check(change_type in ('self_change','teacher_reset')),
  changed_at timestamptz not null default now()
);

alter table public.password_change_audit enable row level security;

drop policy if exists password_change_audit_owner_read on public.password_change_audit;
create policy password_change_audit_owner_read
on public.password_change_audit for select
using (user_id = auth.uid() or public.is_staff());

create or replace function public.refresh_monthly_ranking_winner(
  target_word_set_id uuid,
  target_month date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  winner record;
  range_start timestamptz;
  range_end timestamptz;
begin
  if target_word_set_id is null or target_month is null then return; end if;
  range_start := target_month::timestamp at time zone 'Asia/Seoul';
  range_end := (target_month + interval '1 month')::timestamp at time zone 'Asia/Seoul';

  delete from public.monthly_ranking_history
  where month = target_month and word_set_id = target_word_set_id and rank = 1;

  select
    tr.user_id,
    sum(tr.points)::integer as total_points,
    count(*) filter(where tr.score >= 100) as perfect_count,
    count(*) as test_count
  into winner
  from public.test_results tr
  join public.profiles p on p.id = tr.user_id
  where tr.word_set_id = target_word_set_id
    and tr.status = 'completed'
    and tr.taken_at >= range_start
    and tr.taken_at < range_end
    and tr.points > 0
  group by tr.user_id, p.display_name
  order by total_points desc, perfect_count desc, test_count desc, p.display_name asc
  limit 1;

  if winner.user_id is not null then
    insert into public.monthly_ranking_history
      (month, word_set_id, user_id, rank, points, recorded_at)
    values
      (target_month, target_word_set_id, winner.user_id, 1, winner.total_points, now());
  end if;
end;
$$;

create or replace function public.test_result_refresh_monthly_ranking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data public.test_results;
  month_key date;
begin
  row_data := case when tg_op = 'DELETE' then old else new end;
  if row_data.word_set_id is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;
  month_key := date_trunc(
    'month', row_data.taken_at at time zone 'Asia/Seoul'
  )::date;
  perform public.refresh_monthly_ranking_winner(row_data.word_set_id, month_key);
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists test_results_monthly_ranking_refresh on public.test_results;
create trigger test_results_monthly_ranking_refresh
after insert or update or delete on public.test_results
for each row execute function public.test_result_refresh_monthly_ranking();

-- 기존 기록으로 현재 보유 월의 1위를 한 번 복원합니다.
do $$
declare r record;
begin
  for r in
    select distinct
      word_set_id,
      date_trunc('month', taken_at at time zone 'Asia/Seoul')::date as month_key
    from public.test_results
    where word_set_id is not null
  loop
    perform public.refresh_monthly_ranking_winner(r.word_set_id, r.month_key);
  end loop;
end $$;
