-- Restored from the applied Supabase migration history.
-- UI compatibility identifiers and initial level/emblem settings.

alter table public.wrong_words add column if not exists public_id bigint generated by default as identity;
alter table public.vocabulary_items add column if not exists public_id bigint generated by default as identity;
create unique index if not exists wrong_words_public_id_idx on public.wrong_words(public_id);
create unique index if not exists vocabulary_items_public_id_idx on public.vocabulary_items(public_id);

insert into public.level_settings(level, required_xp, title) values
 (1,0,'단어병아리'),(2,60,'단어병아리'),(3,140,'단어병아리'),(4,240,'단어병아리'),
 (5,360,'단어수집가'),(6,500,'단어수집가'),(7,660,'단어수집가'),(8,840,'단어수집가'),(9,1040,'단어수집가'),
 (10,1260,'단어 포식자'),(11,1500,'단어 포식자'),(12,1760,'단어 포식자'),(13,2040,'단어 포식자'),(14,2340,'단어 포식자'),
 (15,2660,'단어 홀릭'),(16,3000,'단어 홀릭'),(17,3360,'단어 홀릭'),(18,3740,'단어 홀릭'),(19,4140,'단어 홀릭'),
 (20,4560,'단어 학살자'),(21,5000,'단어 학살자'),(22,5460,'단어 학살자'),(23,5940,'단어 학살자'),(24,6440,'단어 학살자'),
 (25,6960,'맑은 눈의 단어광인'),(26,7500,'맑은 눈의 단어광인'),(27,8060,'맑은 눈의 단어광인'),(28,8640,'맑은 눈의 단어광인'),(29,9240,'맑은 눈의 단어광인'),
 (30,9860,'WALKING DICTIONARY')
on conflict(level) do update set required_xp=excluded.required_xp,title=excluded.title;

insert into public.emblem_settings(id,name,image_path,condition_type,condition_value,sort_order,enabled) values
 ('title_chick','단어병아리','./icon.svg','LEVEL','1',1,true),
 ('title_collector','단어수집가','./icon.svg','LEVEL','5',2,true),
 ('title_predator','단어 포식자','./icon.svg','LEVEL','10',3,true),
 ('title_holic','단어 홀릭','./icon.svg','LEVEL','15',4,true),
 ('title_slayer','단어 학살자','./icon.svg','LEVEL','20',5,true),
 ('title_madman','맑은 눈의 단어광인','./icon.svg','LEVEL','25',6,true),
 ('title_dictionary','WALKING DICTIONARY','./icon.svg','LEVEL','30',7,true),
 ('achievement_king','왕의 무게','./icon.svg','MONTHLY_RANK_1','1',8,true),
 ('achievement_success','뭘 해도 성공할 놈','./icon.svg','ATTENDANCE_STREAK','7',9,true),
 ('achievement_madness_max','광기 MAX','./icon.svg','PERFECT_STREAK','10',10,true),
 ('achievement_conqueror','정복자','./icon.svg','CONSECUTIVE_MONTHLY_RANK_1','2',11,true),
 ('achievement_teacher_blessing','T의 가호를 받은 자','./icon.svg','TEACHER_TEST_COUNT','15',12,true),
 ('achievement_reborn','다시 태어나','./icon.svg','ZERO_CORRECT_COUNT','3',13,true),
 ('achievement_vocab_trainer','단어 도감 트레이너','./icon.svg','VOCABULARY_BOOK_COUNT','2',14,true),
 ('achievement_wrong_hunter','오답 사냥꾼','./icon.svg','WRONG_NOTEBOOK_COUNT','30',15,true)
on conflict(id) do update set name=excluded.name,image_path=excluded.image_path,condition_type=excluded.condition_type,
 condition_value=excluded.condition_value,sort_order=excluded.sort_order,enabled=excluded.enabled;

update public.student_experience se set
 level = coalesce((select ls.level from public.level_settings ls where ls.required_xp <= se.total_xp order by ls.required_xp desc limit 1),1),
 title = coalesce((select ls.title from public.level_settings ls where ls.required_xp <= se.total_xp order by ls.required_xp desc limit 1),'단어병아리');
